.TH "CORTEX_LL_EC_CLKSOURCE_HCLK" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_LL_EC_CLKSOURCE_HCLK \- SYSTICK Clock Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLL_SYSTICK_CLKSOURCE_HCLK_DIV8\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBLL_SYSTICK_CLKSOURCE_HCLK\fP   \fBSysTick_CTRL_CLKSOURCE_Msk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define LL_SYSTICK_CLKSOURCE_HCLK   \fBSysTick_CTRL_CLKSOURCE_Msk\fP"
AHB clock selected as SysTick clock source\&. 
.SS "#define LL_SYSTICK_CLKSOURCE_HCLK_DIV8   0x00000000U"
AHB clock divided by 8 selected as SysTick clock source\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
