.TH "CORTEX" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX \- CORTEX
.PP
 \- CORTEX HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCORTEX Exported Types\fP"
.br
.ti -1c
.RI "\fBCORTEX Exported Constants\fP"
.br
.ti -1c
.RI "\fBCORTEX Exported Macros\fP"
.br
.ti -1c
.RI "\fBCORTEX Exported Functions\fP"
.br
.ti -1c
.RI "\fBCORTEX Private Macros\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CORTEX HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
