.TH "CORTEX_LL_Exported_Functions" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_LL_Exported_Functions \- CORTEX Exported Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSYSTICK\fP"
.br
.ti -1c
.RI "\fBLOW POWER MODE\fP"
.br
.ti -1c
.RI "\fBMCU INFO\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
