.TH "CRC_Aliases" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_Aliases \- CRC API aliases
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_CRC_Input_Data_Reverse\fP   HAL_CRCEx_Input_Data_Reverse"
.br
.ti -1c
.RI "#define \fBHAL_CRC_Output_Data_Reverse\fP   HAL_CRCEx_Output_Data_Reverse"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_CRC_Input_Data_Reverse   HAL_CRCEx_Input_Data_Reverse"
Aliased to HAL_CRCEx_Input_Data_Reverse for inter STM32 series compatibility 
.br
 
.SS "#define HAL_CRC_Output_Data_Reverse   HAL_CRCEx_Output_Data_Reverse"
Aliased to HAL_CRCEx_Output_Data_Reverse for inter STM32 series compatibility 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
