.TH "RadarApp/usart_custom Directory Reference" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RadarApp/usart_custom Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBusart_custom\&.c\fP"
.br
.RI "Source file for custom uart handling, consists of all used variables, enums or functions that are connected directly with uart communication\&. "
.ti -1c
.RI "file \fBusart_custom\&.h\fP"
.br
.RI "Header file for custom uart handling, consists of all used variables, enums or functions that are connected directly with uart communication\&. "
.in -1c
