.TH "Core/Src Directory Reference" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdma\&.c\fP"
.br
.RI "This file provides code for the configuration of all the requested memory to memory DMA transfers\&. "
.ti -1c
.RI "file \fBgpio\&.c\fP"
.br
.RI "This file provides code for the configuration of all used GPIO pins\&. "
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Main source file of ultrasonic radar project\&. "
.ti -1c
.RI "file \fBspi\&.c\fP"
.br
.RI "This file provides code for the configuration of the SPI instances\&. "
.ti -1c
.RI "file \fBstm32g0xx_hal_msp\&.c\fP"
.br
.RI "This file provides code for the MSP Initialization and de-Initialization codes\&. "
.ti -1c
.RI "file \fBstm32g0xx_it\&.c\fP"
.br
.RI "Interrupt Service Routines\&. "
.ti -1c
.RI "file \fBsyscalls\&.c\fP"
.br
.RI "STM32CubeIDE Minimal System calls file\&. "
.ti -1c
.RI "file \fBsysmem\&.c\fP"
.br
.RI "STM32CubeIDE System Memory calls file\&. "
.ti -1c
.RI "file \fBsystem_stm32g0xx\&.c\fP"
.br
.RI "CMSIS Cortex-M0+ Device Peripheral Access Layer System Source File\&. "
.ti -1c
.RI "file \fBtim\&.c\fP"
.br
.RI "This file provides code for the configuration of the TIM instances\&. "
.ti -1c
.RI "file \fBusart\&.c\fP"
.br
.RI "This file provides code for the configuration of the USART instances\&. "
.in -1c
