.TH "Drivers/STM32G0xx_HAL_Driver/Src Directory Reference" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32G0xx_HAL_Driver/Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstm32g0xx_hal\&.c\fP"
.br
.RI "HAL module driver\&. This is the common part of the HAL initialization\&. "
.ti -1c
.RI "file \fBstm32g0xx_hal_cortex\&.c\fP"
.br
.RI "CORTEX HAL module driver\&. This file provides firmware functions to manage the following functionalities of the CORTEX: "
.ti -1c
.RI "file \fBstm32g0xx_hal_dma\&.c\fP"
.br
.RI "DMA HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Direct Memory Access (DMA) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_dma_ex\&.c\fP"
.br
.RI "DMA Extension HAL module driver This file provides firmware functions to manage the following functionalities of the DMA Extension peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_exti\&.c\fP"
.br
.RI "EXTI HAL module driver\&. This file provides firmware functions to manage the following functionalities of the General Purpose Input/Output (EXTI) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_flash\&.c\fP"
.br
.RI "FLASH HAL module driver\&. This file provides firmware functions to manage the following functionalities of the internal FLASH memory: "
.ti -1c
.RI "file \fBstm32g0xx_hal_flash_ex\&.c\fP"
.br
.RI "Extended FLASH HAL module driver\&. This file provides firmware functions to manage the following functionalities of the FLASH extended peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_gpio\&.c\fP"
.br
.RI "GPIO HAL module driver\&. This file provides firmware functions to manage the following functionalities of the General Purpose Input/Output (GPIO) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_pwr\&.c\fP"
.br
.RI "PWR HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Power Controller (PWR) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_pwr_ex\&.c\fP"
.br
.RI "Extended PWR HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Power Controller (PWR) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_rcc\&.c\fP"
.br
.RI "RCC HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Reset and Clock Control (RCC) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_rcc_ex\&.c\fP"
.br
.RI "Extended RCC HAL module driver\&. This file provides firmware functions to manage the following functionalities RCC extended peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_spi\&.c\fP"
.br
.RI "SPI HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Serial Peripheral Interface (SPI) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_spi_ex\&.c\fP"
.br
.RI "Extended SPI HAL module driver\&. This file provides firmware functions to manage the following SPI peripheral extended functionalities : "
.ti -1c
.RI "file \fBstm32g0xx_hal_tim\&.c\fP"
.br
.RI "TIM HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Timer (TIM) peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_tim_ex\&.c\fP"
.br
.RI "TIM HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Timer Extended peripheral: "
.ti -1c
.RI "file \fBstm32g0xx_hal_uart\&.c\fP"
.br
.RI "UART HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Universal Asynchronous Receiver Transmitter Peripheral (UART)\&. "
.ti -1c
.RI "file \fBstm32g0xx_hal_uart_ex\&.c\fP"
.br
.RI "Extended UART HAL module driver\&. This file provides firmware functions to manage the following extended functionalities of the Universal Asynchronous Receiver Transmitter Peripheral (UART)\&. "
.ti -1c
.RI "file \fBstm32g0xx_ll_dma\&.c\fP"
.br
.RI "DMA LL module driver\&. "
.ti -1c
.RI "file \fBstm32g0xx_ll_rcc\&.c\fP"
.br
.RI "RCC LL module driver\&. "
.in -1c
