.TH "RadarApp/ServoDriver Directory Reference" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RadarApp/ServoDriver Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBservo_driver\&.c\fP"
.br
.RI "File containing code of servomechanism driver controlled by PWM, which was created for Radar embedded project\&. "
.ti -1c
.RI "file \fBservo_driver\&.h\fP"
.br
.RI "File containing code of servomechanism driver controlled by PWM, which was created for Radar embedded project\&. "
.in -1c
