.TH "Debug/RadarApp/DisplayDriver Directory Reference" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Debug/RadarApp/DisplayDriver Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGFX_Color\&.d\fP"
.br
.ti -1c
.RI "file \fBILI9341\&.d\fP"
.br
.in -1c
