.TH "RadarApp/DistanceSensorDriver Directory Reference" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RadarApp/DistanceSensorDriver Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdistance_sensor\&.c\fP"
.br
.ti -1c
.RI "file \fBdistance_sensor\&.h\fP"
.br
.RI "File containing code of ultrasonic distance sensor, implementation, modifications and making measurement\&. "
.in -1c
