.TH "DMA_flag_definitions" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_flag_definitions \- DMA flag definitions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_FLAG_GI1\fP   \fBDMA_ISR_GIF1\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC1\fP   \fBDMA_ISR_TCIF1\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT1\fP   \fBDMA_ISR_HTIF1\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE1\fP   \fBDMA_ISR_TEIF1\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GI2\fP   \fBDMA_ISR_GIF2\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC2\fP   \fBDMA_ISR_TCIF2\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT2\fP   \fBDMA_ISR_HTIF2\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE2\fP   \fBDMA_ISR_TEIF2\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GI3\fP   \fBDMA_ISR_GIF3\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC3\fP   \fBDMA_ISR_TCIF3\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT3\fP   \fBDMA_ISR_HTIF3\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE3\fP   \fBDMA_ISR_TEIF3\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GI4\fP   \fBDMA_ISR_GIF4\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC4\fP   \fBDMA_ISR_TCIF4\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT4\fP   \fBDMA_ISR_HTIF4\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE4\fP   \fBDMA_ISR_TEIF4\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GI5\fP   \fBDMA_ISR_GIF5\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC5\fP   \fBDMA_ISR_TCIF5\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT5\fP   \fBDMA_ISR_HTIF5\fP"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE5\fP   \fBDMA_ISR_TEIF5\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_FLAG_GI1   \fBDMA_ISR_GIF1\fP"
Global Interrupt flag for Channel 1 
.br
 
.SS "#define DMA_FLAG_GI2   \fBDMA_ISR_GIF2\fP"
Global Interrupt flag for Channel 2 
.br
 
.SS "#define DMA_FLAG_GI3   \fBDMA_ISR_GIF3\fP"
Global Interrupt flag for Channel 3 
.br
 
.SS "#define DMA_FLAG_GI4   \fBDMA_ISR_GIF4\fP"
Global Interrupt flag for Channel 4 
.br
 
.SS "#define DMA_FLAG_GI5   \fBDMA_ISR_GIF5\fP"
Global Interrupt flag for Channel 5 
.br
 
.SS "#define DMA_FLAG_HT1   \fBDMA_ISR_HTIF1\fP"
Half Transfer flag for Channel 1 
.br
 
.SS "#define DMA_FLAG_HT2   \fBDMA_ISR_HTIF2\fP"
Half Transfer flag for Channel 2 
.br
 
.SS "#define DMA_FLAG_HT3   \fBDMA_ISR_HTIF3\fP"
Half Transfer flag for Channel 3 
.br
 
.SS "#define DMA_FLAG_HT4   \fBDMA_ISR_HTIF4\fP"
Half Transfer flag for Channel 4 
.br
 
.SS "#define DMA_FLAG_HT5   \fBDMA_ISR_HTIF5\fP"
Half Transfer flag for Channel 5 
.br
 
.SS "#define DMA_FLAG_TC1   \fBDMA_ISR_TCIF1\fP"
Transfer Complete flag for Channel 1 
.SS "#define DMA_FLAG_TC2   \fBDMA_ISR_TCIF2\fP"
Transfer Complete flag for Channel 2 
.SS "#define DMA_FLAG_TC3   \fBDMA_ISR_TCIF3\fP"
Transfer Complete flag for Channel 3 
.SS "#define DMA_FLAG_TC4   \fBDMA_ISR_TCIF4\fP"
Transfer Complete flag for Channel 4 
.SS "#define DMA_FLAG_TC5   \fBDMA_ISR_TCIF5\fP"
Transfer Complete flag for Channel 5 
.SS "#define DMA_FLAG_TE1   \fBDMA_ISR_TEIF1\fP"
Transfer Error flag for Channel 1 
.br
 
.SS "#define DMA_FLAG_TE2   \fBDMA_ISR_TEIF2\fP"
Transfer Error flag for Channel 2 
.br
 
.SS "#define DMA_FLAG_TE3   \fBDMA_ISR_TEIF3\fP"
Transfer Error flag for Channel 3 
.br
 
.SS "#define DMA_FLAG_TE4   \fBDMA_ISR_TEIF4\fP"
Transfer Error flag for Channel 4 
.br
 
.SS "#define DMA_FLAG_TE5   \fBDMA_ISR_TEIF5\fP"
Transfer Error for Channel 5 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
