.TH "DMA_Peripheral_data_size" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Peripheral_data_size \- DMA Peripheral data size
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_PDATAALIGN_BYTE\fP   LL_DMA_PDATAALIGN_BYTE"
.br
.ti -1c
.RI "#define \fBDMA_PDATAALIGN_HALFWORD\fP   LL_DMA_PDATAALIGN_HALFWORD"
.br
.ti -1c
.RI "#define \fBDMA_PDATAALIGN_WORD\fP   LL_DMA_PDATAALIGN_WORD"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_PDATAALIGN_BYTE   LL_DMA_PDATAALIGN_BYTE"
Peripheral data alignment : Byte 
.br
 
.SS "#define DMA_PDATAALIGN_HALFWORD   LL_DMA_PDATAALIGN_HALFWORD"
Peripheral data alignment : HalfWord 
.SS "#define DMA_PDATAALIGN_WORD   LL_DMA_PDATAALIGN_WORD"
Peripheral data alignment : Word 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
