.TH "DMA_Peripheral_incremented_mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Peripheral_incremented_mode \- DMA Peripheral incremented mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_PINC_ENABLE\fP   LL_DMA_PERIPH_INCREMENT"
.br
.ti -1c
.RI "#define \fBDMA_PINC_DISABLE\fP   LL_DMA_PERIPH_NOINCREMENT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_PINC_DISABLE   LL_DMA_PERIPH_NOINCREMENT"
Peripheral increment mode Disable 
.SS "#define DMA_PINC_ENABLE   LL_DMA_PERIPH_INCREMENT"
Peripheral increment mode Enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
