.TH "DMA_Memory_data_size" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Memory_data_size \- DMA Memory data size
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_MDATAALIGN_BYTE\fP   LL_DMA_MDATAALIGN_BYTE"
.br
.ti -1c
.RI "#define \fBDMA_MDATAALIGN_HALFWORD\fP   LL_DMA_MDATAALIGN_HALFWORD"
.br
.ti -1c
.RI "#define \fBDMA_MDATAALIGN_WORD\fP   LL_DMA_MDATAALIGN_WORD"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_MDATAALIGN_BYTE   LL_DMA_MDATAALIGN_BYTE"
Memory data alignment : Byte 
.br
 
.SS "#define DMA_MDATAALIGN_HALFWORD   LL_DMA_MDATAALIGN_HALFWORD"
Memory data alignment : HalfWord 
.SS "#define DMA_MDATAALIGN_WORD   LL_DMA_MDATAALIGN_WORD"
Memory data alignment : Word 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
