.TH "DMA_Data_transfer_direction" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Data_transfer_direction \- DMA Data transfer direction
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_PERIPH_TO_MEMORY\fP   LL_DMA_DIRECTION_PERIPH_TO_MEMORY"
.br
.ti -1c
.RI "#define \fBDMA_MEMORY_TO_PERIPH\fP   LL_DMA_DIRECTION_MEMORY_TO_PERIPH"
.br
.ti -1c
.RI "#define \fBDMA_MEMORY_TO_MEMORY\fP   LL_DMA_DIRECTION_MEMORY_TO_MEMORY"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_MEMORY_TO_MEMORY   LL_DMA_DIRECTION_MEMORY_TO_MEMORY"
Memory to memory direction 
.br
 
.SS "#define DMA_MEMORY_TO_PERIPH   LL_DMA_DIRECTION_MEMORY_TO_PERIPH"
Memory to peripheral direction 
.SS "#define DMA_PERIPH_TO_MEMORY   LL_DMA_DIRECTION_PERIPH_TO_MEMORY"
Peripheral to memory direction 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
