.TH "DMA_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_TypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIFCR\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DMA_TypeDef::IFCR"
DMA interrupt flag clear register, Address offset: 0x04 
.SS "\fB__IO\fP uint32_t DMA_TypeDef::ISR"
DMA interrupt status register, Address offset: 0x00 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
