.TH "DMA_Memory_incremented_mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Memory_incremented_mode \- DMA Memory incremented mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_MINC_ENABLE\fP   LL_DMA_MEMORY_INCREMENT"
.br
.ti -1c
.RI "#define \fBDMA_MINC_DISABLE\fP   LL_DMA_MEMORY_NOINCREMENT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_MINC_DISABLE   LL_DMA_MEMORY_NOINCREMENT"
Memory increment mode Disable 
.SS "#define DMA_MINC_ENABLE   LL_DMA_MEMORY_INCREMENT"
Memory increment mode Enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
