.TH "DMA_Priority_level" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Priority_level \- DMA Priority level
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_PRIORITY_LOW\fP   LL_DMA_PRIORITY_LOW"
.br
.ti -1c
.RI "#define \fBDMA_PRIORITY_MEDIUM\fP   LL_DMA_PRIORITY_MEDIUM"
.br
.ti -1c
.RI "#define \fBDMA_PRIORITY_HIGH\fP   LL_DMA_PRIORITY_HIGH"
.br
.ti -1c
.RI "#define \fBDMA_PRIORITY_VERY_HIGH\fP   LL_DMA_PRIORITY_VERYHIGH"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_PRIORITY_HIGH   LL_DMA_PRIORITY_HIGH"
Priority level : High 
.br
 
.SS "#define DMA_PRIORITY_LOW   LL_DMA_PRIORITY_LOW"
Priority level : Low 
.br
 
.SS "#define DMA_PRIORITY_MEDIUM   LL_DMA_PRIORITY_MEDIUM"
Priority level : Medium 
.br
 
.SS "#define DMA_PRIORITY_VERY_HIGH   LL_DMA_PRIORITY_VERYHIGH"
Priority level : Very_High 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
