.TH "DMA_Channel_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Channel_TypeDef \- DMA Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCPAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DMA Controller\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CCR"
DMA channel x configuration register 
.br
 
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CMAR"
DMA channel x memory address register 
.br
 
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CNDTR"
DMA channel x number of data register 
.br
 
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CPAR"
DMA channel x peripheral address register 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
