.TH "DMA_mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_mode \- DMA mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_NORMAL\fP   LL_DMA_MODE_NORMAL"
.br
.ti -1c
.RI "#define \fBDMA_CIRCULAR\fP   LL_DMA_MODE_CIRCULAR"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_CIRCULAR   LL_DMA_MODE_CIRCULAR"
Circular mode 
.br
 
.SS "#define DMA_NORMAL   LL_DMA_MODE_NORMAL"
Normal mode 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
