.TH "DMAEx_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx_Exported_Constants \- DMAEx Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDMAMUX SyncSignalID selection\fP"
.br
.ti -1c
.RI "\fBDMAMUX SyncPolarity selection\fP"
.br
.ti -1c
.RI "\fBDMAMUX SignalGeneratorID selection\fP"
.br
.ti -1c
.RI "\fBDMAMUX RequestGeneneratorPolarity selection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
