.TH "DMAEx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx \- DMAEx
.PP
 \- DMA Extended HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDMAEx Exported Types\fP"
.br
.ti -1c
.RI "\fBDMAEx Exported Constants\fP"
.br
.ti -1c
.RI "\fBDMAEx Private Macros\fP"
.br
.RI "DMAEx private macros\&. "
.ti -1c
.RI "\fBDMAEx_Exported_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DMA Extended HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
