.TH "DMAEx_DMAMUX_SyncSignalID_selection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx_DMAMUX_SyncSignalID_selection \- DMAMUX SyncSignalID selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI0\fP   LL_DMAMUX_SYNC_EXTI_LINE0"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI1\fP   LL_DMAMUX_SYNC_EXTI_LINE1"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI2\fP   LL_DMAMUX_SYNC_EXTI_LINE2"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI3\fP   LL_DMAMUX_SYNC_EXTI_LINE3"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI4\fP   LL_DMAMUX_SYNC_EXTI_LINE4"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI5\fP   LL_DMAMUX_SYNC_EXTI_LINE5"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI6\fP   LL_DMAMUX_SYNC_EXTI_LINE6"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI7\fP   LL_DMAMUX_SYNC_EXTI_LINE7"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI8\fP   LL_DMAMUX_SYNC_EXTI_LINE8"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI9\fP   LL_DMAMUX_SYNC_EXTI_LINE9"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI10\fP   LL_DMAMUX_SYNC_EXTI_LINE10"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI11\fP   LL_DMAMUX_SYNC_EXTI_LINE11"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI12\fP   LL_DMAMUX_SYNC_EXTI_LINE12"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI13\fP   LL_DMAMUX_SYNC_EXTI_LINE13"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI14\fP   LL_DMAMUX_SYNC_EXTI_LINE14"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_EXTI15\fP   LL_DMAMUX_SYNC_EXTI_LINE15"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_DMAMUX1_CH0_EVT\fP   LL_DMAMUX_SYNC_DMAMUX_CH0"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_DMAMUX1_CH1_EVT\fP   LL_DMAMUX_SYNC_DMAMUX_CH1"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_DMAMUX1_CH2_EVT\fP   LL_DMAMUX_SYNC_DMAMUX_CH2"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_DMAMUX1_CH3_EVT\fP   LL_DMAMUX_SYNC_DMAMUX_CH3"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_SYNC_TIM14_OC\fP   LL_DMAMUX_SYNC_TIM14_OC"
.br
.ti -1c
.RI "#define \fBHAL_DMAMUX1_MAX_SYNC\fP   \fBHAL_DMAMUX1_SYNC_TIM14_OC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_DMAMUX1_MAX_SYNC   \fBHAL_DMAMUX1_SYNC_TIM14_OC\fP"

.SS "#define HAL_DMAMUX1_SYNC_DMAMUX1_CH0_EVT   LL_DMAMUX_SYNC_DMAMUX_CH0"
Synchronization signal from DMAMUX channel0 Event 
.SS "#define HAL_DMAMUX1_SYNC_DMAMUX1_CH1_EVT   LL_DMAMUX_SYNC_DMAMUX_CH1"
Synchronization signal from DMAMUX channel1 Event 
.SS "#define HAL_DMAMUX1_SYNC_DMAMUX1_CH2_EVT   LL_DMAMUX_SYNC_DMAMUX_CH2"
Synchronization signal from DMAMUX channel2 Event 
.SS "#define HAL_DMAMUX1_SYNC_DMAMUX1_CH3_EVT   LL_DMAMUX_SYNC_DMAMUX_CH3"
Synchronization signal from DMAMUX channel3 Event 
.SS "#define HAL_DMAMUX1_SYNC_EXTI0   LL_DMAMUX_SYNC_EXTI_LINE0"
Synchronization signal from EXTI Line0 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI1   LL_DMAMUX_SYNC_EXTI_LINE1"
Synchronization signal from EXTI Line1 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI10   LL_DMAMUX_SYNC_EXTI_LINE10"
Synchronization signal from EXTI Line10 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI11   LL_DMAMUX_SYNC_EXTI_LINE11"
Synchronization signal from EXTI Line11 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI12   LL_DMAMUX_SYNC_EXTI_LINE12"
Synchronization signal from EXTI Line12 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI13   LL_DMAMUX_SYNC_EXTI_LINE13"
Synchronization signal from EXTI Line1 3 
.SS "#define HAL_DMAMUX1_SYNC_EXTI14   LL_DMAMUX_SYNC_EXTI_LINE14"
Synchronization signal from EXTI Line1 4 
.SS "#define HAL_DMAMUX1_SYNC_EXTI15   LL_DMAMUX_SYNC_EXTI_LINE15"
Synchronization signal from EXTI Line1 5 
.SS "#define HAL_DMAMUX1_SYNC_EXTI2   LL_DMAMUX_SYNC_EXTI_LINE2"
Synchronization signal from EXTI Line2 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI3   LL_DMAMUX_SYNC_EXTI_LINE3"
Synchronization signal from EXTI Line3 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI4   LL_DMAMUX_SYNC_EXTI_LINE4"
Synchronization signal from EXTI Line4 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI5   LL_DMAMUX_SYNC_EXTI_LINE5"
Synchronization signal from EXTI Line5 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI6   LL_DMAMUX_SYNC_EXTI_LINE6"
Synchronization signal from EXTI Line6 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI7   LL_DMAMUX_SYNC_EXTI_LINE7"
Synchronization signal from EXTI Line7 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI8   LL_DMAMUX_SYNC_EXTI_LINE8"
Synchronization signal from EXTI Line8 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_EXTI9   LL_DMAMUX_SYNC_EXTI_LINE9"
Synchronization signal from EXTI Line9 
.br
 
.SS "#define HAL_DMAMUX1_SYNC_TIM14_OC   LL_DMAMUX_SYNC_TIM14_OC"
Synchronization signal from TIM14 OC 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
