.TH "DMAEx_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx_Exported_Functions_Group1 \- DMAEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMAEx_ConfigMuxRequestGenerator\fP (\fBDMA_HandleTypeDef\fP *hdma, \fBHAL_DMA_MuxRequestGeneratorConfigTypeDef\fP *pRequestGeneratorConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMAEx_EnableMuxRequestGenerator\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMAEx_DisableMuxRequestGenerator\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMAEx_ConfigMuxSync\fP (\fBDMA_HandleTypeDef\fP *hdma, \fBHAL_DMA_MuxSyncConfigTypeDef\fP *pSyncConfig)"
.br
.ti -1c
.RI "void \fBHAL_DMAEx_MUX_IRQHandler\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_DMAEx_ConfigMuxRequestGenerator (\fBDMA_HandleTypeDef\fP * hdma, \fBHAL_DMA_MuxRequestGeneratorConfigTypeDef\fP * pRequestGeneratorConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_DMAEx_ConfigMuxSync (\fBDMA_HandleTypeDef\fP * hdma, \fBHAL_DMA_MuxSyncConfigTypeDef\fP * pSyncConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_DMAEx_DisableMuxRequestGenerator (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "\fBHAL_StatusTypeDef\fP HAL_DMAEx_EnableMuxRequestGenerator (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void HAL_DMAEx_MUX_IRQHandler (\fBDMA_HandleTypeDef\fP * hdma)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
