.TH "DMAEx_Exported_Types" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAEx_Exported_Types \- DMAEx Exported Types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHAL_DMA_MuxSyncConfigTypeDef\fP"
.br
.RI "HAL DMAMUX Synchronization configuration structure definition\&. "
.ti -1c
.RI "struct \fBHAL_DMA_MuxRequestGeneratorConfigTypeDef\fP"
.br
.RI "HAL DMAMUX request generator parameters structure definition\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
