.TH "DMAMUX_Channel_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMAMUX_Channel_TypeDef \- DMA Multiplexer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DMA Multiplexer\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DMAMUX_Channel_TypeDef::CCR"
DMA Multiplexer Channel x Control Register Address offset: 0x0004 * (channel x) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
