.TH "drawHelperStruct" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drawHelperStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBdrawScale\fP"
.br
.ti -1c
.RI "uint8_t \fBmeasureScalesNumber\fP"
.br
.ti -1c
.RI "uint16_t * \fBmeasureScaleY\fP"
.br
.ti -1c
.RI "uint16_t * \fBmeasureScaleCm\fP"
.br
.ti -1c
.RI "int16_t \fBxp\fP"
.br
.ti -1c
.RI "int16_t \fByp\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double drawHelperStruct::drawScale"

.SS "uint16_t* drawHelperStruct::measureScaleCm"

.SS "uint8_t drawHelperStruct::measureScalesNumber"

.SS "uint16_t* drawHelperStruct::measureScaleY"

.SS "int16_t drawHelperStruct::xp"

.SS "int16_t drawHelperStruct::yp"


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
