.TH "FLASH_OB_USER_IWDG_STOP" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_IWDG_STOP \- FLASH Option Bytes User IWDG Mode On Stop
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_IWDG_STOP_FREEZE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_IWDG_STOP_RUN\fP   \fBFLASH_OPTR_IWDG_STOP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_IWDG_STOP_FREEZE   0x00000000U"
Independent watchdog counter is frozen in Stop mode 
.SS "#define OB_IWDG_STOP_RUN   \fBFLASH_OPTR_IWDG_STOP\fP"
Independent watchdog counter is running in Stop mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
