.TH "FLASH_OB_USER_IWDG_STANDBY" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_IWDG_STANDBY \- FLASH Option Bytes User IWDG Mode On Standby
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_IWDG_STDBY_FREEZE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_IWDG_STDBY_RUN\fP   \fBFLASH_OPTR_IWDG_STDBY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_IWDG_STDBY_FREEZE   0x00000000U"
Independent watchdog counter is frozen in Standby mode 
.SS "#define OB_IWDG_STDBY_RUN   \fBFLASH_OPTR_IWDG_STDBY\fP"
Independent watchdog counter is running in Standby mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
