.TH "FLASH_OB_USER_nRST_STANDBY" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_nRST_STANDBY \- FLASH Option Bytes User Reset On Standby
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_STANDBY_RST\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_STANDBY_NORST\fP   \fBFLASH_OPTR_nRST_STDBY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_STANDBY_NORST   \fBFLASH_OPTR_nRST_STDBY\fP"
No reset generated when entering the standby mode 
.SS "#define OB_STANDBY_RST   0x00000000U"
Reset generated when entering the standby mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
