.TH "FLASH_Type_Program" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Type_Program \- FLASH Program Type
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_TYPEPROGRAM_DOUBLEWORD\fP   \fBFLASH_CR_PG\fP"
.br
.ti -1c
.RI "#define \fBFLASH_TYPEPROGRAM_FAST\fP   \fBFLASH_CR_FSTPG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_TYPEPROGRAM_DOUBLEWORD   \fBFLASH_CR_PG\fP"
Program a double-word (64-bit) at a specified address 
.SS "#define FLASH_TYPEPROGRAM_FAST   \fBFLASH_CR_FSTPG\fP"
Fast program a 32 row double-word (64-bit) at a specified address 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
