.TH "FLASH_OB_USER_nBOOT_SEL" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_nBOOT_SEL \- FLASH Option Bytes User Boot0 Selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_BOOT0_FROM_PIN\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_BOOT0_FROM_OB\fP   \fBFLASH_OPTR_nBOOT_SEL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_BOOT0_FROM_OB   \fBFLASH_OPTR_nBOOT_SEL\fP"
BOOT0 signal is defined by nBOOT0 option bit 
.SS "#define OB_BOOT0_FROM_PIN   0x00000000U"
BOOT0 signal is defined by PA14/BOOT0 pin value 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
