.TH "FLASH_OB_USER_IWDG_SW" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_IWDG_SW \- FLASH Option Bytes User IWDG Type
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_IWDG_HW\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_IWDG_SW\fP   \fBFLASH_OPTR_IWDG_SW\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_IWDG_HW   0x00000000U"
Hardware independent watchdog 
.SS "#define OB_IWDG_SW   \fBFLASH_OPTR_IWDG_SW\fP"
Software independent watchdog 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
