.TH "FLASHEx_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Exported_Functions_Group1 \- FLASHEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit, uint32_t *PageError)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase_IT\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_EnableDebugger\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_DisableDebugger\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_FLASHEx_FlashEmptyCheck\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_ForceFlashEmpty\fP (uint32_t FlashEmpty)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_OBProgram\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.ti -1c
.RI "void \fBHAL_FLASHEx_OBGetConfig\fP (\fBFLASH_OBProgramInitTypeDef\fP *pOBInit)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_FLASHEx_DisableDebugger (void)"

.SS "void HAL_FLASHEx_EnableDebugger (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_Erase (\fBFLASH_EraseInitTypeDef\fP * pEraseInit, uint32_t * PageError)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_Erase_IT (\fBFLASH_EraseInitTypeDef\fP * pEraseInit)"

.SS "uint32_t HAL_FLASHEx_FlashEmptyCheck (void)"

.SS "void HAL_FLASHEx_ForceFlashEmpty (uint32_t FlashEmpty)"

.SS "void HAL_FLASHEx_OBGetConfig (\fBFLASH_OBProgramInitTypeDef\fP * pOBInit)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_OBProgram (\fBFLASH_OBProgramInitTypeDef\fP * pOBInit)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
