.TH "FLASH_Latency" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Latency \- FLASH Latency
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_LATENCY_0\fP   0x00000000UL"
.br
.ti -1c
.RI "#define \fBFLASH_LATENCY_1\fP   \fBFLASH_ACR_LATENCY_0\fP"
.br
.ti -1c
.RI "#define \fBFLASH_LATENCY_2\fP   \fBFLASH_ACR_LATENCY_1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_LATENCY_0   0x00000000UL"
FLASH Zero wait state 
.SS "#define FLASH_LATENCY_1   \fBFLASH_ACR_LATENCY_0\fP"
FLASH One wait state 
.SS "#define FLASH_LATENCY_2   \fBFLASH_ACR_LATENCY_1\fP"
FLASH Two wait states 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
