.TH "FLASH_OB_Read_Protection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_Read_Protection \- FLASH Option Bytes Read Protection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_RDP_LEVEL_0\fP   0x000000AAU"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL_1\fP   0x000000BBU"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL_2\fP   0x000000CCU"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_RDP_LEVEL_0   0x000000AAU"

.SS "#define OB_RDP_LEVEL_1   0x000000BBU"

.SS "#define OB_RDP_LEVEL_2   0x000000CCU"
Warning: When enabling read protection level 2 it is no more possible to go back to level 1 or 0 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
