.TH "FLASH_OB_USER_nBOOT0" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_nBOOT0 \- FLASH Option Bytes User nBOOT0 option bit
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_nBOOT0_RESET\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_nBOOT0_SET\fP   \fBFLASH_OPTR_nBOOT0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_nBOOT0_RESET   0x00000000U"
nBOOT0 = 0 
.SS "#define OB_nBOOT0_SET   \fBFLASH_OPTR_nBOOT0\fP"
nBOOT0 = 1 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
