.TH "FLASHEx_Private_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Private_Macros \- FLASHEx Private Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_FLASH_EMPTY_CHECK\fP(__VALUE__)   (((__VALUE__) == \fBFLASH_PROG_EMPTY\fP) || ((__VALUE__) == \fBFLASH_PROG_NOT_EMPTY\fP))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFLASH_PageErase\fP (uint32_t Banks, uint32_t Page)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_FLASH_EMPTY_CHECK(__VALUE__)   (((__VALUE__) == \fBFLASH_PROG_EMPTY\fP) || ((__VALUE__) == \fBFLASH_PROG_NOT_EMPTY\fP))"

.SH "Function Documentation"
.PP 
.SS "void FLASH_PageErase (uint32_t Banks, uint32_t Page)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
