.TH "FLASH_OB_USER_nRST_STOP" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_nRST_STOP \- FLASH Option Bytes User Reset On Stop
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_STOP_RST\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_STOP_NORST\fP   \fBFLASH_OPTR_nRST_STOP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_STOP_NORST   \fBFLASH_OPTR_nRST_STOP\fP"
No reset generated when entering the stop mode 
.SS "#define OB_STOP_RST   0x00000000U"
Reset generated when entering the stop mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
