.TH "FLASH_Error" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Error \- FLASH Error
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_OP\fP   \fBFLASH_SR_OPERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_PROG\fP   \fBFLASH_SR_PROGERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_WRP\fP   \fBFLASH_SR_WRPERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_PGA\fP   \fBFLASH_SR_PGAERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_SIZ\fP   \fBFLASH_SR_SIZERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_PGS\fP   \fBFLASH_SR_PGSERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_MIS\fP   \fBFLASH_SR_MISERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_FAST\fP   \fBFLASH_SR_FASTERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_OPTV\fP   \fBFLASH_SR_OPTVERR\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_ECCD\fP   \fBFLASH_ECCR_ECCD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_FLASH_ERROR_ECCD   \fBFLASH_ECCR_ECCD\fP"

.SS "#define HAL_FLASH_ERROR_FAST   \fBFLASH_SR_FASTERR\fP"

.SS "#define HAL_FLASH_ERROR_MIS   \fBFLASH_SR_MISERR\fP"

.SS "#define HAL_FLASH_ERROR_NONE   0x00000000U"

.SS "#define HAL_FLASH_ERROR_OP   \fBFLASH_SR_OPERR\fP"

.SS "#define HAL_FLASH_ERROR_OPTV   \fBFLASH_SR_OPTVERR\fP"

.SS "#define HAL_FLASH_ERROR_PGA   \fBFLASH_SR_PGAERR\fP"

.SS "#define HAL_FLASH_ERROR_PGS   \fBFLASH_SR_PGSERR\fP"

.SS "#define HAL_FLASH_ERROR_PROG   \fBFLASH_SR_PROGERR\fP"

.SS "#define HAL_FLASH_ERROR_SIZ   \fBFLASH_SR_SIZERR\fP"

.SS "#define HAL_FLASH_ERROR_WRP   \fBFLASH_SR_WRPERR\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
