.TH "FLASHEx_Empty_Check" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Empty_Check \- FLASHEx Empty Check
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_PROG_NOT_EMPTY\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBFLASH_PROG_EMPTY\fP   \fBFLASH_ACR_PROGEMPTY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_PROG_EMPTY   \fBFLASH_ACR_PROGEMPTY\fP"
1st location in Flash is empty 
.SS "#define FLASH_PROG_NOT_EMPTY   0x00000000u"
1st location in Flash is programmed 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
