.TH "FLASH_OB_USER_SRAM_PARITY" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_SRAM_PARITY \- FLASH Option Bytes User SRAM parity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_SRAM_PARITY_ENABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_SRAM_PARITY_DISABLE\fP   \fBFLASH_OPTR_RAM_PARITY_CHECK\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_SRAM_PARITY_DISABLE   \fBFLASH_OPTR_RAM_PARITY_CHECK\fP"
Sram parity disable 
.SS "#define OB_SRAM_PARITY_ENABLE   0x00000000U"
Sram parity enable 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
