.TH "FLASH_Exported_Variables" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Exported_Variables \- FLASH Exported Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFLASH_ProcessTypeDef\fP \fBpFlash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "\fBFLASH_ProcessTypeDef\fP pFlash\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
