.TH "FLASH_OB_USER_WWDG_SW" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_OB_USER_WWDG_SW \- FLASH Option Bytes User WWDG Type
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_WWDG_HW\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBOB_WWDG_SW\fP   \fBFLASH_OPTR_WWDG_SW\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_WWDG_HW   0x00000000U"
Hardware window watchdog 
.SS "#define OB_WWDG_SW   \fBFLASH_OPTR_WWDG_SW\fP"
Software window watchdog 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
