.TH "FLASHEx_Private_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Private_Constants \- FLASHEx Private Constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_PCROP_GRANULARITY_OFFSET\fP   9u"
.br
.ti -1c
.RI "#define \fBFLASH_PCROP_GRANULARITY\fP   (1UL << \fBFLASH_PCROP_GRANULARITY_OFFSET\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_PCROP_GRANULARITY   (1UL << \fBFLASH_PCROP_GRANULARITY_OFFSET\fP)"
FLASH Code Readout Protection granularity, 512 Bytes 
.SS "#define FLASH_PCROP_GRANULARITY_OFFSET   9u"
FLASH Code Readout Protection granularity offset 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
