.TH "RadarApp/DisplayDriver/fonts/font_8x5.h" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RadarApp/DisplayDriver/fonts/font_8x5.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint8_t \fBfont_8x5\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const uint8_t font_8x5[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
