.TH "GPIO" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO \- GPIO
.PP
 \- GPIO HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGPIO Exported Types\fP"
.br
.ti -1c
.RI "\fBGPIO Exported Constants\fP"
.br
.ti -1c
.RI "\fBGPIO Exported Macros\fP"
.br
.ti -1c
.RI "\fBGPIO Private Constants\fP"
.br
.ti -1c
.RI "\fBGPIO Private Macros\fP"
.br
.ti -1c
.RI "\fBGPIO Exported Functions\fP"
.br
.RI "GPIO Exported Functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
GPIO HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
