.TH "GPIO_Exported_Functions" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Functions \- GPIO Exported Functions
.PP
 \- GPIO Exported Functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBInitialization/de\-initialization functions\fP"
.br
.RI "Initialization and Configuration functions\&. "
.ti -1c
.RI "\fBIO operation functions\fP"
.br
.RI "IO operation functions\&. "
.in -1c
.SH "Detailed Description"
.PP 
GPIO Exported Functions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
