.TH "GPIO_speed" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_speed \- GPIO speed
.PP
 \- GPIO Output Maximum frequency\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_LOW\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_MEDIUM\fP   0x00000001u"
.br
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_HIGH\fP   0x00000002u"
.br
.ti -1c
.RI "#define \fBGPIO_SPEED_FREQ_VERY_HIGH\fP   0x00000003u"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPIO Output Maximum frequency\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define GPIO_SPEED_FREQ_HIGH   0x00000002u"
High speed 
.br
 
.SS "#define GPIO_SPEED_FREQ_LOW   0x00000000u"
Low speed 
.br
 
.SS "#define GPIO_SPEED_FREQ_MEDIUM   0x00000001u"
Medium speed 
.br
 
.SS "#define GPIO_SPEED_FREQ_VERY_HIGH   0x00000003u"
Very high speed 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
