.TH "GPIO_InitTypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_InitTypeDef \- GPIO Init structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g0xx_hal_gpio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBPin\fP"
.br
.ti -1c
.RI "uint32_t \fBMode\fP"
.br
.ti -1c
.RI "uint32_t \fBPull\fP"
.br
.ti -1c
.RI "uint32_t \fBSpeed\fP"
.br
.ti -1c
.RI "uint32_t \fBAlternate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPIO Init structure definition\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t GPIO_InitTypeDef::Alternate"
Peripheral to be connected to the selected pins This parameter can be a value of \fBGPIOEx Alternate function selection\fP 
.SS "uint32_t GPIO_InitTypeDef::Mode"
Specifies the operating mode for the selected pins\&. This parameter can be a value of \fBGPIO mode\fP 
.SS "uint32_t GPIO_InitTypeDef::Pin"
Specifies the GPIO pins to be configured\&. This parameter can be any value of \fBGPIO pins\fP 
.SS "uint32_t GPIO_InitTypeDef::Pull"
Specifies the Pull-up or Pull-Down activation for the selected pins\&. This parameter can be a value of \fBGPIO pull\fP 
.SS "uint32_t GPIO_InitTypeDef::Speed"
Specifies the speed for the selected pins\&. This parameter can be a value of \fBGPIO speed\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
