.TH "GPIO_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Exported_Functions_Group1 \- Initialization/de-initialization functions
.PP
 \- Initialization and Configuration functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_GPIO_Init\fP (\fBGPIO_TypeDef\fP *GPIOx, \fBGPIO_InitTypeDef\fP *GPIO_Init)"
.br
.ti -1c
.RI "void \fBHAL_GPIO_DeInit\fP (\fBGPIO_TypeDef\fP *GPIOx, uint32_t GPIO_Pin)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initialization and Configuration functions\&. 


.SH "Function Documentation"
.PP 
.SS "void HAL_GPIO_DeInit (\fBGPIO_TypeDef\fP * GPIOx, uint32_t GPIO_Pin)"

.SS "void HAL_GPIO_Init (\fBGPIO_TypeDef\fP * GPIOx, \fBGPIO_InitTypeDef\fP * GPIO_Init)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
