.TH "HAL" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL \- HAL
.PP
 \- HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTick Frequency\fP"
.br
.ti -1c
.RI "\fBHAL Exported Constants\fP"
.br
.ti -1c
.RI "\fBHAL Exported Macros\fP"
.br
.ti -1c
.RI "\fBSYSCFG Private Macros\fP"
.br
.ti -1c
.RI "\fBHAL Private Macros\fP"
.br
.ti -1c
.RI "\fBHAL Exported Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
