.TH "HAL_I2S_Aliased_Defines" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2S_Aliased_Defines \- HAL I2S Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2S_STANDARD_PHILLIPS\fP   I2S_STANDARD_PHILIPS"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define I2S_STANDARD_PHILLIPS   I2S_STANDARD_PHILIPS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
