.TH "HAL_SPI_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SPI_Aliased_Macros \- HAL SPI Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_SPI_1LINE_TX\fP   \fBSPI_1LINE_TX\fP"
.br
.ti -1c
.RI "#define \fB__HAL_SPI_1LINE_RX\fP   \fBSPI_1LINE_RX\fP"
.br
.ti -1c
.RI "#define \fB__HAL_SPI_RESET_CRC\fP   \fBSPI_RESET_CRC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_SPI_1LINE_RX   \fBSPI_1LINE_RX\fP"

.SS "#define __HAL_SPI_1LINE_TX   \fBSPI_1LINE_TX\fP"

.SS "#define __HAL_SPI_RESET_CRC   \fBSPI_RESET_CRC\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
