.TH "HAL_Exported_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Macros \- HAL Exported Macros
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDBG Exported Macros\fP"
.br
.ti -1c
.RI "\fBSYSCFG Exported Macros\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
