.TH "HAL_Pin_remapping" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Pin_remapping \- Pin remapping
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYSCFG_REMAP_PA11\fP   \fBSYSCFG_CFGR1_PA11_RMP\fP"
.br
.ti -1c
.RI "#define \fBSYSCFG_REMAP_PA12\fP   \fBSYSCFG_CFGR1_PA12_RMP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SYSCFG_REMAP_PA11   \fBSYSCFG_CFGR1_PA11_RMP\fP"
PA11 pad behaves digitally as PA9 GPIO pin 
.SS "#define SYSCFG_REMAP_PA12   \fBSYSCFG_CFGR1_PA12_RMP\fP"
PA12 pad behaves digitally as PA10 GPIO pin 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
