.TH "HAL_SPI_Aliased_Defines" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SPI_Aliased_Defines \- HAL SPI Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_TIMODE_DISABLED\fP   \fBSPI_TIMODE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_TIMODE_ENABLED\fP   \fBSPI_TIMODE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_DISABLED\fP   \fBSPI_CRCCALCULATION_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_ENABLED\fP   \fBSPI_CRCCALCULATION_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_NSS_PULSE_DISABLED\fP   \fBSPI_NSS_PULSE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBSPI_NSS_PULSE_ENABLED\fP   \fBSPI_NSS_PULSE_ENABLE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_CRCCALCULATION_DISABLED   \fBSPI_CRCCALCULATION_DISABLE\fP"

.SS "#define SPI_CRCCALCULATION_ENABLED   \fBSPI_CRCCALCULATION_ENABLE\fP"

.SS "#define SPI_NSS_PULSE_DISABLED   \fBSPI_NSS_PULSE_DISABLE\fP"

.SS "#define SPI_NSS_PULSE_ENABLED   \fBSPI_NSS_PULSE_ENABLE\fP"

.SS "#define SPI_TIMODE_DISABLED   \fBSPI_TIMODE_DISABLE\fP"

.SS "#define SPI_TIMODE_ENABLED   \fBSPI_TIMODE_ENABLE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
