.TH "HAL_UART_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_UART_Aliased_Macros \- HAL UART Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_UART_GETCLOCKSOURCE\fP   UART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__HAL_UART_MASK_COMPUTATION\fP   \fBUART_MASK_COMPUTATION\fP"
.br
.ti -1c
.RI "#define \fB__UART_GETCLOCKSOURCE\fP   UART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__UART_MASK_COMPUTATION\fP   \fBUART_MASK_COMPUTATION\fP"
.br
.ti -1c
.RI "#define \fBIS_UART_WAKEUPMETHODE\fP   \fBIS_UART_WAKEUPMETHOD\fP"
.br
.ti -1c
.RI "#define \fBIS_UART_ONEBIT_SAMPLE\fP   \fBIS_UART_ONE_BIT_SAMPLE\fP"
.br
.ti -1c
.RI "#define \fBIS_UART_ONEBIT_SAMPLING\fP   \fBIS_UART_ONE_BIT_SAMPLE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_UART_GETCLOCKSOURCE   UART_GETCLOCKSOURCE"

.SS "#define __HAL_UART_MASK_COMPUTATION   \fBUART_MASK_COMPUTATION\fP"

.SS "#define __UART_GETCLOCKSOURCE   UART_GETCLOCKSOURCE"

.SS "#define __UART_MASK_COMPUTATION   \fBUART_MASK_COMPUTATION\fP"

.SS "#define IS_UART_ONEBIT_SAMPLE   \fBIS_UART_ONE_BIT_SAMPLE\fP"

.SS "#define IS_UART_ONEBIT_SAMPLING   \fBIS_UART_ONE_BIT_SAMPLE\fP"

.SS "#define IS_UART_WAKEUPMETHODE   \fBIS_UART_WAKEUPMETHOD\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
