.TH "HAL_FLASH_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_FLASH_Aliased_Macros \- HAL FLASH Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_WRPAREA\fP   \fBIS_OB_WRPAREA\fP"
.br
.ti -1c
.RI "#define \fBIS_TYPEPROGRAM\fP   \fBIS_FLASH_TYPEPROGRAM\fP"
.br
.ti -1c
.RI "#define \fBIS_TYPEPROGRAMFLASH\fP   \fBIS_FLASH_TYPEPROGRAM\fP"
.br
.ti -1c
.RI "#define \fBIS_TYPEERASE\fP   \fBIS_FLASH_TYPEERASE\fP"
.br
.ti -1c
.RI "#define \fBIS_NBSECTORS\fP   IS_FLASH_NBSECTORS"
.br
.ti -1c
.RI "#define \fBIS_OB_WDG_SOURCE\fP   IS_OB_IWDG_SOURCE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_NBSECTORS   IS_FLASH_NBSECTORS"

.SS "#define IS_OB_WDG_SOURCE   IS_OB_IWDG_SOURCE"

.SS "#define IS_TYPEERASE   \fBIS_FLASH_TYPEERASE\fP"

.SS "#define IS_TYPEPROGRAM   \fBIS_FLASH_TYPEPROGRAM\fP"

.SS "#define IS_TYPEPROGRAMFLASH   \fBIS_FLASH_TYPEPROGRAM\fP"

.SS "#define IS_WRPAREA   \fBIS_OB_WRPAREA\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
