.TH "HAL_I2S_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2S_Aliased_Macros \- HAL I2S Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_I2S_INSTANCE\fP   \fBIS_I2S_ALL_INSTANCE\fP"
.br
.ti -1c
.RI "#define \fBIS_I2S_INSTANCE_EXT\fP   IS_I2S_ALL_INSTANCE_EXT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_I2S_INSTANCE   \fBIS_I2S_ALL_INSTANCE\fP"

.SS "#define IS_I2S_INSTANCE_EXT   IS_I2S_ALL_INSTANCE_EXT"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
