.TH "HAL_PPP_Aliased_Functions" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_PPP_Aliased_Functions \- HAL PPP Aliased Functions maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
