.TH "HAL_PWR_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_PWR_Aliased_Macros \- HAL PWR Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_PVD_EVENT_DISABLE\fP   __HAL_PWR_PVD_EXTI_DISABLE_EVENT"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EVENT_ENABLE\fP   __HAL_PWR_PVD_EXTI_ENABLE_EVENT"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_FALLINGTRIGGER_DISABLE\fP   __HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_FALLINGTRIGGER_ENABLE\fP   __HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_RISINGTRIGGER_DISABLE\fP   __HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_RISINGTRIGGER_ENABLE\fP   __HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EVENT_DISABLE\fP   __HAL_PWR_PVM_EVENT_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EVENT_ENABLE\fP   __HAL_PWR_PVM_EVENT_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_FALLINGTRIGGER_DISABLE\fP   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_FALLINGTRIGGER_ENABLE\fP   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_RISINGTRIGGER_DISABLE\fP   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_RISINGTRIGGER_ENABLE\fP   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_INTERNALWAKEUP_DISABLE\fP   \fBHAL_PWREx_DisableInternalWakeUpLine\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_INTERNALWAKEUP_ENABLE\fP   \fBHAL_PWREx_EnableInternalWakeUpLine\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PULL_UP_DOWN_CONFIG_DISABLE\fP   \fBHAL_PWREx_DisablePullUpPullDownConfig\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PULL_UP_DOWN_CONFIG_ENABLE\fP   \fBHAL_PWREx_EnablePullUpPullDownConfig\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_CLEAR_EGDE_TRIGGER\fP()   do { __HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE();__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE(); } while(0)"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_EVENT_DISABLE\fP   __HAL_PWR_PVD_EXTI_DISABLE_EVENT"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_EVENT_ENABLE\fP   __HAL_PWR_PVD_EXTI_ENABLE_EVENT"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_FALLINGTRIGGER_DISABLE\fP   __HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_FALLINGTRIGGER_ENABLE\fP   __HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_RISINGTRIGGER_DISABLE\fP   __HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_RISINGTRIGGER_ENABLE\fP   __HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_SET_RISING_EDGE_TRIGGER\fP   __HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVM_DISABLE\fP()   do { HAL_PWREx_DisablePVM1();HAL_PWREx_DisablePVM2();HAL_PWREx_DisablePVM3();HAL_PWREx_DisablePVM4(); } while(0)"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVM_ENABLE\fP()   do { HAL_PWREx_EnablePVM1();HAL_PWREx_EnablePVM2();HAL_PWREx_EnablePVM3();HAL_PWREx_EnablePVM4(); } while(0)"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_SRAM2CONTENT_PRESERVE_DISABLE\fP   HAL_PWREx_DisableSRAM2ContentRetention"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_SRAM2CONTENT_PRESERVE_ENABLE\fP   HAL_PWREx_EnableSRAM2ContentRetention"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_DISABLE\fP   HAL_PWREx_DisableVddIO2"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_ENABLE\fP   HAL_PWREx_EnableVddIO2"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_EXTI_CLEAR_EGDE_TRIGGER\fP   __HAL_PWR_VDDIO2_EXTI_DISABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_PWR_VDDIO2_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDUSB_DISABLE\fP   HAL_PWREx_DisableVddUSB"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDUSB_ENABLE\fP   HAL_PWREx_EnableVddUSB"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_CLEAR_FLAG\fP   __HAL_PWR_PVD_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_DISABLE_IT\fP   __HAL_PWR_PVD_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_ENABLE_IT\fP   __HAL_PWR_PVD_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_GENERATE_SWIT\fP   __HAL_PWR_PVD_EXTI_GENERATE_SWIT"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_GET_FLAG\fP   __HAL_PWR_PVD_EXTI_GET_FLAG"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_PVD_EVENT_DISABLE   __HAL_PWR_PVD_EXTI_DISABLE_EVENT"

.SS "#define __HAL_PVD_EVENT_ENABLE   __HAL_PWR_PVD_EXTI_ENABLE_EVENT"

.SS "#define __HAL_PVD_EXTI_CLEAR_FLAG   __HAL_PWR_PVD_EXTI_CLEAR_FLAG"

.SS "#define __HAL_PVD_EXTI_DISABLE_IT   __HAL_PWR_PVD_EXTI_DISABLE_IT"

.SS "#define __HAL_PVD_EXTI_ENABLE_IT   __HAL_PWR_PVD_EXTI_ENABLE_IT"

.SS "#define __HAL_PVD_EXTI_FALLINGTRIGGER_DISABLE   __HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE"

.SS "#define __HAL_PVD_EXTI_FALLINGTRIGGER_ENABLE   __HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_PVD_EXTI_GENERATE_SWIT   __HAL_PWR_PVD_EXTI_GENERATE_SWIT"

.SS "#define __HAL_PVD_EXTI_GET_FLAG   __HAL_PWR_PVD_EXTI_GET_FLAG"

.SS "#define __HAL_PVD_EXTI_RISINGTRIGGER_DISABLE   __HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE"

.SS "#define __HAL_PVD_EXTI_RISINGTRIGGER_ENABLE   __HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE"

.SS "#define __HAL_PVM_EVENT_DISABLE   __HAL_PWR_PVM_EVENT_DISABLE"

.SS "#define __HAL_PVM_EVENT_ENABLE   __HAL_PWR_PVM_EVENT_ENABLE"

.SS "#define __HAL_PVM_EXTI_FALLINGTRIGGER_DISABLE   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_DISABLE"

.SS "#define __HAL_PVM_EXTI_FALLINGTRIGGER_ENABLE   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_ENABLE"

.SS "#define __HAL_PVM_EXTI_RISINGTRIGGER_DISABLE   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_DISABLE"

.SS "#define __HAL_PVM_EXTI_RISINGTRIGGER_ENABLE   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_ENABLE"

.SS "#define __HAL_PWR_INTERNALWAKEUP_DISABLE   \fBHAL_PWREx_DisableInternalWakeUpLine\fP"

.SS "#define __HAL_PWR_INTERNALWAKEUP_ENABLE   \fBHAL_PWREx_EnableInternalWakeUpLine\fP"

.SS "#define __HAL_PWR_PULL_UP_DOWN_CONFIG_DISABLE   \fBHAL_PWREx_DisablePullUpPullDownConfig\fP"

.SS "#define __HAL_PWR_PULL_UP_DOWN_CONFIG_ENABLE   \fBHAL_PWREx_EnablePullUpPullDownConfig\fP"

.SS "#define __HAL_PWR_PVD_EXTI_CLEAR_EGDE_TRIGGER()   do { __HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE();__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE(); } while(0)"

.SS "#define __HAL_PWR_PVD_EXTI_EVENT_DISABLE   __HAL_PWR_PVD_EXTI_DISABLE_EVENT"

.SS "#define __HAL_PWR_PVD_EXTI_EVENT_ENABLE   __HAL_PWR_PVD_EXTI_ENABLE_EVENT"

.SS "#define __HAL_PWR_PVD_EXTI_FALLINGTRIGGER_DISABLE   __HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_PVD_EXTI_FALLINGTRIGGER_ENABLE   __HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_PVD_EXTI_RISINGTRIGGER_DISABLE   __HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE"

.SS "#define __HAL_PWR_PVD_EXTI_RISINGTRIGGER_ENABLE   __HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE"

.SS "#define __HAL_PWR_PVD_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_PVD_EXTI_SET_RISING_EDGE_TRIGGER   __HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE"

.SS "#define __HAL_PWR_PVM_DISABLE()   do { HAL_PWREx_DisablePVM1();HAL_PWREx_DisablePVM2();HAL_PWREx_DisablePVM3();HAL_PWREx_DisablePVM4(); } while(0)"

.SS "#define __HAL_PWR_PVM_ENABLE()   do { HAL_PWREx_EnablePVM1();HAL_PWREx_EnablePVM2();HAL_PWREx_EnablePVM3();HAL_PWREx_EnablePVM4(); } while(0)"

.SS "#define __HAL_PWR_SRAM2CONTENT_PRESERVE_DISABLE   HAL_PWREx_DisableSRAM2ContentRetention"

.SS "#define __HAL_PWR_SRAM2CONTENT_PRESERVE_ENABLE   HAL_PWREx_EnableSRAM2ContentRetention"

.SS "#define __HAL_PWR_VDDIO2_DISABLE   HAL_PWREx_DisableVddIO2"

.SS "#define __HAL_PWR_VDDIO2_ENABLE   HAL_PWREx_EnableVddIO2"

.SS "#define __HAL_PWR_VDDIO2_EXTI_CLEAR_EGDE_TRIGGER   __HAL_PWR_VDDIO2_EXTI_DISABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_VDDIO2_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_PWR_VDDIO2_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_VDDUSB_DISABLE   HAL_PWREx_DisableVddUSB"

.SS "#define __HAL_PWR_VDDUSB_ENABLE   HAL_PWREx_EnableVddUSB"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
