.TH "HAL_Exported_Functions_Group3" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Functions_Group3 \- DBGMCU Control functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGStopMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGStopMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGStandbyMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGStandbyMode\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_DBGMCU_DisableDBGStandbyMode (void)"

.SS "void HAL_DBGMCU_DisableDBGStopMode (void)"

.SS "void HAL_DBGMCU_EnableDBGStandbyMode (void)"

.SS "void HAL_DBGMCU_EnableDBGStopMode (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
