.TH "HAL_CRC_Aliased_Defines" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_CRC_Aliased_Defines \- HAL CRC Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCRC_OUTPUTDATA_INVERSION_DISABLED\fP   CRC_OUTPUTDATA_INVERSION_DISABLE"
.br
.ti -1c
.RI "#define \fBCRC_OUTPUTDATA_INVERSION_ENABLED\fP   CRC_OUTPUTDATA_INVERSION_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CRC_OUTPUTDATA_INVERSION_DISABLED   CRC_OUTPUTDATA_INVERSION_DISABLE"

.SS "#define CRC_OUTPUTDATA_INVERSION_ENABLED   CRC_OUTPUTDATA_INVERSION_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
