.TH "HAL_UART_Aliased_Defines" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_UART_Aliased_Defines \- HAL UART Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ONEBIT_SAMPLING_DISABLED\fP   \fBUART_ONE_BIT_SAMPLE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBUART_ONEBIT_SAMPLING_ENABLED\fP   \fBUART_ONE_BIT_SAMPLE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_DISABLED\fP   \fBUART_ONE_BIT_SAMPLE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_ENABLED\fP   \fBUART_ONE_BIT_SAMPLE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UART_ONEBIT_ENABLE\fP   \fB__HAL_UART_ONE_BIT_SAMPLE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UART_ONEBIT_DISABLE\fP   \fB__HAL_UART_ONE_BIT_SAMPLE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__DIV_SAMPLING16\fP   \fBUART_DIV_SAMPLING16\fP"
.br
.ti -1c
.RI "#define \fB__DIVMANT_SAMPLING16\fP   UART_DIVMANT_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__DIVFRAQ_SAMPLING16\fP   UART_DIVFRAQ_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__UART_BRR_SAMPLING16\fP   UART_BRR_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__DIV_SAMPLING8\fP   \fBUART_DIV_SAMPLING8\fP"
.br
.ti -1c
.RI "#define \fB__DIVMANT_SAMPLING8\fP   UART_DIVMANT_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__DIVFRAQ_SAMPLING8\fP   UART_DIVFRAQ_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__UART_BRR_SAMPLING8\fP   UART_BRR_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__DIV_LPUART\fP   \fBUART_DIV_LPUART\fP"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHODE_IDLELINE\fP   \fBUART_WAKEUPMETHOD_IDLELINE\fP"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHODE_ADDRESSMARK\fP   \fBUART_WAKEUPMETHOD_ADDRESSMARK\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __DIV_LPUART   \fBUART_DIV_LPUART\fP"

.SS "#define __DIV_SAMPLING16   \fBUART_DIV_SAMPLING16\fP"

.SS "#define __DIV_SAMPLING8   \fBUART_DIV_SAMPLING8\fP"

.SS "#define __DIVFRAQ_SAMPLING16   UART_DIVFRAQ_SAMPLING16"

.SS "#define __DIVFRAQ_SAMPLING8   UART_DIVFRAQ_SAMPLING8"

.SS "#define __DIVMANT_SAMPLING16   UART_DIVMANT_SAMPLING16"

.SS "#define __DIVMANT_SAMPLING8   UART_DIVMANT_SAMPLING8"

.SS "#define __HAL_UART_ONEBIT_DISABLE   \fB__HAL_UART_ONE_BIT_SAMPLE_DISABLE\fP"

.SS "#define __HAL_UART_ONEBIT_ENABLE   \fB__HAL_UART_ONE_BIT_SAMPLE_ENABLE\fP"

.SS "#define __UART_BRR_SAMPLING16   UART_BRR_SAMPLING16"

.SS "#define __UART_BRR_SAMPLING8   UART_BRR_SAMPLING8"

.SS "#define UART_ONE_BIT_SAMPLE_DISABLED   \fBUART_ONE_BIT_SAMPLE_DISABLE\fP"

.SS "#define UART_ONE_BIT_SAMPLE_ENABLED   \fBUART_ONE_BIT_SAMPLE_ENABLE\fP"

.SS "#define UART_ONEBIT_SAMPLING_DISABLED   \fBUART_ONE_BIT_SAMPLE_DISABLE\fP"

.SS "#define UART_ONEBIT_SAMPLING_ENABLED   \fBUART_ONE_BIT_SAMPLE_ENABLE\fP"

.SS "#define UART_WAKEUPMETHODE_ADDRESSMARK   \fBUART_WAKEUPMETHOD_ADDRESSMARK\fP"

.SS "#define UART_WAKEUPMETHODE_IDLELINE   \fBUART_WAKEUPMETHOD_IDLELINE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
