.TH "HAL_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Functions_Group1 \- HAL Initialization and Configuration functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_Init\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DeInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_MspInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_MspDeInit\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_InitTick\fP (uint32_t TickPriority)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_DeInit (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_Init (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_InitTick (uint32_t TickPriority)"

.SS "void HAL_MspDeInit (void)"

.SS "void HAL_MspInit (void)"
Initializes the Global MSP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
