.TH "HAL_Exported_Variables" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Variables \- HAL_Exported_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBuwTick\fP"
.br
.ti -1c
.RI "uint32_t \fBuwTickPrio\fP"
.br
.ti -1c
.RI "\fBHAL_TickFreqTypeDef\fP \fBuwTickFreq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "\fB__IO\fP uint32_t uwTick\fC [extern]\fP"

.SS "\fBHAL_TickFreqTypeDef\fP uwTickFreq\fC [extern]\fP"

.SS "uint32_t uwTickPrio\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
