.TH "HAL_RNG_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_RNG_Aliased_Macros \- HAL RNG Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_RNG_ReadyCallback\fP(__HANDLE__)   HAL_RNG_ReadyDataCallback((__HANDLE__), uint32_t random32bit)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_RNG_ReadyCallback(__HANDLE__)   HAL_RNG_ReadyDataCallback((__HANDLE__), uint32_t random32bit)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
