.TH "HAL_WWDG_Aliased_Defines" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_WWDG_Aliased_Defines \- HAL WWDG Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCFR_BASE\fP   WWDG_CFR_BASE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CFR_BASE   WWDG_CFR_BASE"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
