.TH "HAL_SD_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SD_Aliased_Macros \- HAL SD/MMC Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSD_OCR_CID_CSD_OVERWRIETE\fP   SD_OCR_CID_CSD_OVERWRITE"
.br
.ti -1c
.RI "#define \fBSD_CMD_SD_APP_STAUS\fP   SD_CMD_SD_APP_STATUS"
.br
.ti -1c
.RI "#define \fBeMMC_HIGH_VOLTAGE_RANGE\fP   EMMC_HIGH_VOLTAGE_RANGE"
.br
.ti -1c
.RI "#define \fBeMMC_DUAL_VOLTAGE_RANGE\fP   EMMC_DUAL_VOLTAGE_RANGE"
.br
.ti -1c
.RI "#define \fBeMMC_LOW_VOLTAGE_RANGE\fP   EMMC_LOW_VOLTAGE_RANGE"
.br
.ti -1c
.RI "#define \fBSDMMC_NSpeed_CLK_DIV\fP   SDMMC_NSPEED_CLK_DIV"
.br
.ti -1c
.RI "#define \fBSDMMC_HSpeed_CLK_DIV\fP   SDMMC_HSPEED_CLK_DIV"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define eMMC_DUAL_VOLTAGE_RANGE   EMMC_DUAL_VOLTAGE_RANGE"

.SS "#define eMMC_HIGH_VOLTAGE_RANGE   EMMC_HIGH_VOLTAGE_RANGE"

.SS "#define eMMC_LOW_VOLTAGE_RANGE   EMMC_LOW_VOLTAGE_RANGE"

.SS "#define SD_CMD_SD_APP_STAUS   SD_CMD_SD_APP_STATUS"

.SS "#define SD_OCR_CID_CSD_OVERWRIETE   SD_OCR_CID_CSD_OVERWRITE"

.SS "#define SDMMC_HSpeed_CLK_DIV   SDMMC_HSPEED_CLK_DIV"

.SS "#define SDMMC_NSpeed_CLK_DIV   SDMMC_NSPEED_CLK_DIV"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
