.TH "HAL_IR_POL_SEL" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_IR_POL_SEL \- IR output polarity selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_SYSCFG_IRDA_POLARITY_NOT_INVERTED\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBHAL_SYSCFG_IRDA_POLARITY_INVERTED\fP   \fBSYSCFG_CFGR1_IR_POL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_SYSCFG_IRDA_POLARITY_INVERTED   \fBSYSCFG_CFGR1_IR_POL\fP"
01: IR output polarity inverted 
.SS "#define HAL_SYSCFG_IRDA_POLARITY_NOT_INVERTED   0x00000000U"
00: IR output polarity not inverted 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
