.TH "HAL_Exported_Functions_Group4" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Functions_Group4 \- SYSCFG configuration functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_SYSCFG_EnableIOAnalogSwitchBooster\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SYSCFG_DisableIOAnalogSwitchBooster\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SYSCFG_EnableRemap\fP (uint32_t PinRemap)"
.br
.ti -1c
.RI "void \fBHAL_SYSCFG_DisableRemap\fP (uint32_t PinRemap)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_SYSCFG_DisableIOAnalogSwitchBooster (void)"

.SS "void HAL_SYSCFG_DisableRemap (uint32_t PinRemap)"

.SS "void HAL_SYSCFG_EnableIOAnalogSwitchBooster (void)"

.SS "void HAL_SYSCFG_EnableRemap (uint32_t PinRemap)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
