.TH "HAL_GPIO_Aliased_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_GPIO_Aliased_Macros \- HAL GPIO Aliased Macros maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGET_GPIO_SOURCE\fP   \fBGPIO_GET_INDEX\fP"
.br
.ti -1c
.RI "#define \fBGET_GPIO_INDEX\fP   \fBGPIO_GET_INDEX\fP"
.br
.ti -1c
.RI "#define \fBGPIO_AF0_LPTIM\fP   GPIO_AF0_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF1_LPTIM\fP   GPIO_AF1_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF2_LPTIM\fP   GPIO_AF2_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF6_DFSDM\fP   GPIO_AF6_DFSDM1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GET_GPIO_INDEX   \fBGPIO_GET_INDEX\fP"

.SS "#define GET_GPIO_SOURCE   \fBGPIO_GET_INDEX\fP"

.SS "#define GPIO_AF0_LPTIM   GPIO_AF0_LPTIM1"

.SS "#define GPIO_AF1_LPTIM   GPIO_AF1_LPTIM1"

.SS "#define GPIO_AF2_LPTIM   GPIO_AF2_LPTIM1"

.SS "#define GPIO_AF6_DFSDM   GPIO_AF6_DFSDM1"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
