.TH "HASH_alias" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HASH_alias \- HASH API alias
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_HASHEx_IRQHandler\fP   HAL_HASH_IRQHandler"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_HASHEx_IRQHandler   HAL_HASH_IRQHandler"
Redirection for compatibility with legacy code 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
