.TH "IWDG_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_TypeDef \- Independent WATCHDOG\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWINR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Independent WATCHDOG\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::KR"
IWDG Key register, Address offset: 0x00 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::PR"
IWDG Prescaler register, Address offset: 0x04 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::RLR"
IWDG Reload register, Address offset: 0x08 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::SR"
IWDG Status register, Address offset: 0x0C 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::WINR"
IWDG Window register, Address offset: 0x10 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
