.TH "LL_FSMC_Aliased_Defines" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LL_FSMC_Aliased_Defines \- LL FSMC Aliased Defines maintained for legacy purpose
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSMC_NORSRAM_TYPEDEF\fP   FSMC_NORSRAM_TypeDef"
.br
.ti -1c
.RI "#define \fBFSMC_NORSRAM_EXTENDED_TYPEDEF\fP   FSMC_NORSRAM_EXTENDED_TypeDef"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSMC_NORSRAM_EXTENDED_TYPEDEF   FSMC_NORSRAM_EXTENDED_TypeDef"

.SS "#define FSMC_NORSRAM_TYPEDEF   FSMC_NORSRAM_TypeDef"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
