.TH "PWR_Regulator_state_in_SLEEP_STOP_mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Regulator_state_in_SLEEP_STOP_mode \- PWR regulator mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_MAINREGULATOR_ON\fP   (0x00000000u)"
.br
.ti -1c
.RI "#define \fBPWR_LOWPOWERREGULATOR_ON\fP   \fBPWR_CR1_LPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_LOWPOWERREGULATOR_ON   \fBPWR_CR1_LPR\fP"
Regulator in low-power mode 
.SS "#define PWR_MAINREGULATOR_ON   (0x00000000u)"
Regulator in main mode 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
