.TH "PWR_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_TypeDef \- Power Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPUCRA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPDCRA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPUCRB\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPDCRB\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPUCRC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPDCRC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPUCRD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPDCRD\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPUCRF\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPDCRF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Power Control\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::CR1"
PWR Power Control Register 1, Address offset: 0x00 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::CR3"
PWR Power Control Register 3, Address offset: 0x08 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::CR4"
PWR Power Control Register 4, Address offset: 0x0C 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PDCRA"
PWR Pull-Down Control Register of port A, Address offset: 0x24 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PDCRB"
PWR Pull-Down Control Register of port B, Address offset: 0x2C 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PDCRC"
PWR Pull-Down Control Register of port C, Address offset: 0x34 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PDCRD"
PWR Pull-Down Control Register of port D, Address offset: 0x3C 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PDCRF"
PWR Pull-Down Control Register of port F, Address offset: 0x4C 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PUCRA"
PWR Pull-Up Control Register of port A, Address offset: 0x20 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PUCRB"
PWR Pull-Up Control Register of port B, Address offset: 0x28 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PUCRC"
PWR Pull-Up Control Register of port C, Address offset: 0x30 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PUCRD"
PWR Pull-Up Control Register of port D, Address offset: 0x38 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::PUCRF"
PWR Pull-Up Control Register of port F, Address offset: 0x48 
.SS "uint32_t PWR_TypeDef::RESERVED0"
Reserved, Address offset: 0x04 
.SS "uint32_t PWR_TypeDef::RESERVED1"
Reserved, Address offset: 0x1C 
.SS "uint32_t PWR_TypeDef::RESERVED2"
Reserved, Address offset: 0x40 
.SS "uint32_t PWR_TypeDef::RESERVED3"
Reserved, Address offset: 0x44 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::SCR"
PWR Power Status Clear Register, Address offset: 0x18 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::SR1"
PWR Power Status Register 1, Address offset: 0x10 
.SS "\fB__IO\fP uint32_t PWR_TypeDef::SR2"
PWR Power Status Register 2, Address offset: 0x14 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
