.TH "PWR_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Constants \- PWR Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPWR WakeUp pins\fP"
.br
.ti -1c
.RI "\fBPWR Low Power Mode Selection\fP"
.br
.ti -1c
.RI "\fBPWR regulator mode\fP"
.br
.ti -1c
.RI "\fBPWR SLEEP mode entry\fP"
.br
.ti -1c
.RI "\fBPWR STOP mode entry\fP"
.br
.ti -1c
.RI "\fBPWR Status Flags\fP"
.br
.RI "Elements values convention: 0000 00XX 000Y YYYYb\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
