.TH "PWR_Exported_Functions_Group2" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Functions_Group2 \- Peripheral Control functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_PWR_EnableBkUpAccess\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableBkUpAccess\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableWakeUpPin\fP (uint32_t WakeUpPinPolarity)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableWakeUpPin\fP (uint32_t WakeUpPinx)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSLEEPMode\fP (uint32_t Regulator, uint8_t SLEEPEntry)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSTOPMode\fP (uint32_t Regulator, uint8_t STOPEntry)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnterSTANDBYMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableSleepOnExit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableSleepOnExit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableSEVOnPend\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableSEVOnPend\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_PWR_DisableBkUpAccess (void)"

.SS "void HAL_PWR_DisableSEVOnPend (void)"

.SS "void HAL_PWR_DisableSleepOnExit (void)"

.SS "void HAL_PWR_DisableWakeUpPin (uint32_t WakeUpPinx)"

.SS "void HAL_PWR_EnableBkUpAccess (void)"

.SS "void HAL_PWR_EnableSEVOnPend (void)"

.SS "void HAL_PWR_EnableSleepOnExit (void)"

.SS "void HAL_PWR_EnableWakeUpPin (uint32_t WakeUpPinPolarity)"

.SS "void HAL_PWR_EnterSLEEPMode (uint32_t Regulator, uint8_t SLEEPEntry)"

.SS "void HAL_PWR_EnterSTANDBYMode (void)"

.SS "void HAL_PWR_EnterSTOPMode (uint32_t Regulator, uint8_t STOPEntry)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
