.TH "PWR_STOP_mode_entry" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_STOP_mode_entry \- PWR STOP mode entry
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_STOPENTRY_WFI\fP   ((uint8_t)0x01u)"
.br
.ti -1c
.RI "#define \fBPWR_STOPENTRY_WFE\fP   ((uint8_t)0x02u)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_STOPENTRY_WFE   ((uint8_t)0x02u)"
Wait For Event instruction to enter Stop mode 
.br
 
.SS "#define PWR_STOPENTRY_WFI   ((uint8_t)0x01u)"
Wait For Interruption instruction to enter Stop mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
