.TH "PWR_WUP_Polarity" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_WUP_Polarity \- Shift to apply to retrieve polarity information from PWR_WAKEUP_PINy_xxx constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_WUP_POLARITY_SHIFT\fP   0x08u"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_WUP_POLARITY_SHIFT   0x08u"
Internal constant used to retrieve wakeup pin polariry 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
