.TH "PWREx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx \- PWREx
.PP
 \- PWR Extended HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPWR Extended Exported Types\fP"
.br
.ti -1c
.RI "\fBPWR Extended Exported Constants\fP"
.br
.ti -1c
.RI "\fBPWR Extended Private Defines\fP"
.br
.ti -1c
.RI "\fBPWR Extended Exported Functions\fP"
.br
.ti -1c
.RI "\fBPWR Extended Exported Macros\fP"
.br
.ti -1c
.RI "\fBPWR Extended Private Macros\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PWR Extended HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
