.TH "PWREx_VBAT_Battery_Charging_Selection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_VBAT_Battery_Charging_Selection \- PWR battery charging resistor selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_BATTERY_CHARGING_RESISTOR_5\fP   (0x00000000u)"
.br
.ti -1c
.RI "#define \fBPWR_BATTERY_CHARGING_RESISTOR_1_5\fP   \fBPWR_CR4_VBRS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_BATTERY_CHARGING_RESISTOR_1_5   \fBPWR_CR4_VBRS\fP"
VBAT charging through a 1\&.5 kOhms resistor 
.SS "#define PWR_BATTERY_CHARGING_RESISTOR_5   (0x00000000u)"
VBAT charging through a 5 kOhms resistor 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
