.TH "PWREx_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_Exported_Constants \- PWR Extended Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPWR battery charging resistor selection\fP"
.br
.ti -1c
.RI "\fBGPIO bit position\fP"
.br
.RI "for I/O pull up/down setting in standby/shutdown mode "
.ti -1c
.RI "\fBGPIO Port\fP"
.br
.ti -1c
.RI "\fBFlash Power Down modes\fP"
.br
.ti -1c
.RI "\fBPWR Regulator voltage scale\fP"
.br
.ti -1c
.RI "\fBPWR Status Flags\fP"
.br
.RI "Elements values convention: 0000 00XX 000Y YYYYb\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
