.TH "PWREx_Flash_PowerDown" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_Flash_PowerDown \- Flash Power Down modes
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_FLASHPD_LPRUN\fP   \fBPWR_CR1_FPD_LPRUN\fP"
.br
.ti -1c
.RI "#define \fBPWR_FLASHPD_LPSLEEP\fP   \fBPWR_CR1_FPD_LPSLP\fP"
.br
.ti -1c
.RI "#define \fBPWR_FLASHPD_STOP\fP   \fBPWR_CR1_FPD_STOP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_FLASHPD_LPRUN   \fBPWR_CR1_FPD_LPRUN\fP"
Enable Flash power down in low power run mode 
.SS "#define PWR_FLASHPD_LPSLEEP   \fBPWR_CR1_FPD_LPSLP\fP"
Enable Flash power down in low power sleep mode 
.SS "#define PWR_FLASHPD_STOP   \fBPWR_CR1_FPD_STOP\fP"
Enable Flash power down in stop mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
