.TH "PWREx_GPIO_Port" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_GPIO_Port \- GPIO Port
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_GPIO_A\fP   (0x00000000u)"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_B\fP   (0x00000001u)"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_C\fP   (0x00000002u)"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_D\fP   (0x00000003u)"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_F\fP   (0x00000005u)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_GPIO_A   (0x00000000u)"
GPIO port A 
.SS "#define PWR_GPIO_B   (0x00000001u)"
GPIO port B 
.SS "#define PWR_GPIO_C   (0x00000002u)"
GPIO port C 
.SS "#define PWR_GPIO_D   (0x00000003u)"
GPIO port D 
.SS "#define PWR_GPIO_F   (0x00000005u)"
GPIO port F 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
