.TH "PWREx_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_Exported_Functions_Group1 \- Extended Peripheral Control functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_PWREx_EnableBatteryCharging\fP (uint32_t ResistorSelection)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_DisableBatteryCharging\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_EnableInternalWakeUpLine\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_DisableInternalWakeUpLine\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_EnableGPIOPullUp\fP (uint32_t GPIO, uint32_t GPIONumber)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_DisableGPIOPullUp\fP (uint32_t GPIO, uint32_t GPIONumber)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_EnableGPIOPullDown\fP (uint32_t GPIO, uint32_t GPIONumber)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_DisableGPIOPullDown\fP (uint32_t GPIO, uint32_t GPIONumber)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_EnablePullUpPullDownConfig\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_DisablePullUpPullDownConfig\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_EnableFlashPowerDown\fP (uint32_t PowerMode)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_DisableFlashPowerDown\fP (uint32_t PowerMode)"
.br
.ti -1c
.RI "uint32_t \fBHAL_PWREx_GetVoltageRange\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_ControlVoltageScaling\fP (uint32_t VoltageScaling)"
.br
.ti -1c
.RI "void \fBHAL_PWREx_EnableLowPowerRunMode\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_PWREx_DisableLowPowerRunMode\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_ControlVoltageScaling (uint32_t VoltageScaling)"

.SS "void HAL_PWREx_DisableBatteryCharging (void)"

.SS "void HAL_PWREx_DisableFlashPowerDown (uint32_t PowerMode)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_DisableGPIOPullDown (uint32_t GPIO, uint32_t GPIONumber)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_DisableGPIOPullUp (uint32_t GPIO, uint32_t GPIONumber)"

.SS "void HAL_PWREx_DisableInternalWakeUpLine (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_DisableLowPowerRunMode (void)"

.SS "void HAL_PWREx_DisablePullUpPullDownConfig (void)"

.SS "void HAL_PWREx_EnableBatteryCharging (uint32_t ResistorSelection)"

.SS "void HAL_PWREx_EnableFlashPowerDown (uint32_t PowerMode)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_EnableGPIOPullDown (uint32_t GPIO, uint32_t GPIONumber)"

.SS "\fBHAL_StatusTypeDef\fP HAL_PWREx_EnableGPIOPullUp (uint32_t GPIO, uint32_t GPIONumber)"

.SS "void HAL_PWREx_EnableInternalWakeUpLine (void)"

.SS "void HAL_PWREx_EnableLowPowerRunMode (void)"

.SS "void HAL_PWREx_EnablePullUpPullDownConfig (void)"

.SS "uint32_t HAL_PWREx_GetVoltageRange (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
