.TH "PWREx_GPIO_Bit_Number" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_GPIO_Bit_Number \- GPIO bit position
.PP
 \- for I/O pull up/down setting in standby/shutdown mode  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_0\fP   \fBPWR_PUCRB_PU0\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_1\fP   \fBPWR_PUCRB_PU1\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_2\fP   \fBPWR_PUCRB_PU2\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_3\fP   \fBPWR_PUCRB_PU3\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_4\fP   \fBPWR_PUCRB_PU4\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_5\fP   \fBPWR_PUCRB_PU5\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_6\fP   \fBPWR_PUCRB_PU6\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_7\fP   \fBPWR_PUCRB_PU7\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_8\fP   \fBPWR_PUCRB_PU8\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_9\fP   \fBPWR_PUCRB_PU9\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_10\fP   \fBPWR_PUCRB_PU10\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_11\fP   \fBPWR_PUCRB_PU11\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_12\fP   \fBPWR_PUCRB_PU12\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_13\fP   \fBPWR_PUCRB_PU13\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_14\fP   \fBPWR_PUCRB_PU14\fP"
.br
.ti -1c
.RI "#define \fBPWR_GPIO_BIT_15\fP   \fBPWR_PUCRB_PU15\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
for I/O pull up/down setting in standby/shutdown mode 


.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_GPIO_BIT_0   \fBPWR_PUCRB_PU0\fP"
GPIO port I/O pin 0 
.br
 
.SS "#define PWR_GPIO_BIT_1   \fBPWR_PUCRB_PU1\fP"
GPIO port I/O pin 1 
.br
 
.SS "#define PWR_GPIO_BIT_10   \fBPWR_PUCRB_PU10\fP"
GPIO port I/O pin 10 
.SS "#define PWR_GPIO_BIT_11   \fBPWR_PUCRB_PU11\fP"
GPIO port I/O pin 11 
.SS "#define PWR_GPIO_BIT_12   \fBPWR_PUCRB_PU12\fP"
GPIO port I/O pin 12 
.SS "#define PWR_GPIO_BIT_13   \fBPWR_PUCRB_PU13\fP"
GPIO port I/O pin 13 
.SS "#define PWR_GPIO_BIT_14   \fBPWR_PUCRB_PU14\fP"
GPIO port I/O pin 14 
.SS "#define PWR_GPIO_BIT_15   \fBPWR_PUCRB_PU15\fP"
GPIO port I/O pin 15 
.SS "#define PWR_GPIO_BIT_2   \fBPWR_PUCRB_PU2\fP"
GPIO port I/O pin 2 
.br
 
.SS "#define PWR_GPIO_BIT_3   \fBPWR_PUCRB_PU3\fP"
GPIO port I/O pin 3 
.br
 
.SS "#define PWR_GPIO_BIT_4   \fBPWR_PUCRB_PU4\fP"
GPIO port I/O pin 4 
.br
 
.SS "#define PWR_GPIO_BIT_5   \fBPWR_PUCRB_PU5\fP"
GPIO port I/O pin 5 
.br
 
.SS "#define PWR_GPIO_BIT_6   \fBPWR_PUCRB_PU6\fP"
GPIO port I/O pin 6 
.br
 
.SS "#define PWR_GPIO_BIT_7   \fBPWR_PUCRB_PU7\fP"
GPIO port I/O pin 7 
.br
 
.SS "#define PWR_GPIO_BIT_8   \fBPWR_PUCRB_PU8\fP"
GPIO port I/O pin 8 
.br
 
.SS "#define PWR_GPIO_BIT_9   \fBPWR_PUCRB_PU9\fP"
GPIO port I/O pin 9 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
