.TH "PWREx_Regulator_Voltage_Scale" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWREx_Regulator_Voltage_Scale \- PWR Regulator voltage scale
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_REGULATOR_VOLTAGE_SCALE1\fP   \fBPWR_CR1_VOS_0\fP"
.br
.ti -1c
.RI "#define \fBPWR_REGULATOR_VOLTAGE_SCALE2\fP   \fBPWR_CR1_VOS_1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_REGULATOR_VOLTAGE_SCALE1   \fBPWR_CR1_VOS_0\fP"
Voltage scaling range 1 
.SS "#define PWR_REGULATOR_VOLTAGE_SCALE2   \fBPWR_CR1_VOS_1\fP"
Voltage scaling range 2 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
