.TH "RCC_IOPORT_Clock_Sleep_Enabled_Disabled_Status" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_IOPORT_Clock_Sleep_Enabled_Disabled_Status \- IOPORT Clock Sleep Enabled or Disabled Status
.PP
 \- Check whether the IOPORT clock during Low Power (Sleep) mode is enabled or not\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_IS_CLK_SLEEP_ENABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOASMEN\fP)!= \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_IS_CLK_SLEEP_ENABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOBSMEN\fP)!= \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_IS_CLK_SLEEP_ENABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOCSMEN\fP)!= \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOD_IS_CLK_SLEEP_ENABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIODSMEN\fP)!= \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOF_IS_CLK_SLEEP_ENABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOFSMEN\fP)!= \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_IS_CLK_SLEEP_DISABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOASMEN\fP) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_IS_CLK_SLEEP_DISABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOBSMEN\fP) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_IS_CLK_SLEEP_DISABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOCSMEN\fP) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOD_IS_CLK_SLEEP_DISABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIODSMEN\fP) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOF_IS_CLK_SLEEP_DISABLED\fP()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOFSMEN\fP) == \fBRESET\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Check whether the IOPORT clock during Low Power (Sleep) mode is enabled or not\&. 


.PP
\fBNote\fP
.RS 4
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption\&. 
.PP
After wakeup from SLEEP mode, the peripheral clock is enabled again\&. 
.PP
By default, all peripheral clocks are enabled during SLEEP mode\&. 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_GPIOA_IS_CLK_SLEEP_DISABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOASMEN\fP) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOA_IS_CLK_SLEEP_ENABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOASMEN\fP)!= \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOB_IS_CLK_SLEEP_DISABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOBSMEN\fP) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOB_IS_CLK_SLEEP_ENABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOBSMEN\fP)!= \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOC_IS_CLK_SLEEP_DISABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOCSMEN\fP) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOC_IS_CLK_SLEEP_ENABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOCSMEN\fP)!= \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOD_IS_CLK_SLEEP_DISABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIODSMEN\fP) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOD_IS_CLK_SLEEP_ENABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIODSMEN\fP)!= \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOF_IS_CLK_SLEEP_DISABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOFSMEN\fP) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOF_IS_CLK_SLEEP_ENABLED()   (\fBREAD_BIT\fP(\fBRCC\fP\->IOPSMENR, \fBRCC_IOPSMENR_GPIOFSMEN\fP)!= \fBRESET\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
