.TH "RCC_LSI_Config" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_LSI_Config \- LSI Config
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_LSI_OFF\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_LSI_ON\fP   \fBRCC_CSR_LSION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_LSI_OFF   0x00000000U"
LSI clock deactivation 
.SS "#define RCC_LSI_ON   \fBRCC_CSR_LSION\fP"
LSI clock activation 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
