.TH "RCC_Private_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Private_Constants \- RCC_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCR_REG_INDEX\fP   1U"
.br
.ti -1c
.RI "#define \fBBDCR_REG_INDEX\fP   2U"
.br
.ti -1c
.RI "#define \fBCSR_REG_INDEX\fP   3U"
.br
.ti -1c
.RI "#define \fBRCC_FLAG_MASK\fP   0x1FU"
.br
.ti -1c
.RI "#define \fBRCC_CLOCKTYPE_ALL\fP   (\fBRCC_CLOCKTYPE_SYSCLK\fP | \fBRCC_CLOCKTYPE_HCLK\fP | \fBRCC_CLOCKTYPE_PCLK1\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define BDCR_REG_INDEX   2U"

.SS "#define CR_REG_INDEX   1U"

.SS "#define CSR_REG_INDEX   3U"

.SS "#define RCC_CLOCKTYPE_ALL   (\fBRCC_CLOCKTYPE_SYSCLK\fP | \fBRCC_CLOCKTYPE_HCLK\fP | \fBRCC_CLOCKTYPE_PCLK1\fP)"
All clocktype to configure 
.SS "#define RCC_FLAG_MASK   0x1FU"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
