.TH "RCC_APB2_Force_Release_Reset" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB2_Force_Release_Reset \- APB2 Peripheral Force Release Reset
.PP
 \- Force or release APB2 peripheral reset\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_APB2_FORCE_RESET\fP()   \fBWRITE_REG\fP(\fBRCC\fP\->APBRSTR2, 0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SYSCFGRST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM1RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SPI1RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_USART1RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM14_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM14RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM16_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM16RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM17_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM17RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC_FORCE_RESET\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_ADCRST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_APB2_RELEASE_RESET\fP()   \fBWRITE_REG\fP(\fBRCC\fP\->APBRSTR2, 0x00U)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SYSCFGRST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM1RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SPI1RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_USART1RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM14_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM14RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM16_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM16RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM17_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM17RST\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC_RELEASE_RESET\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_ADCRST\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Force or release APB2 peripheral reset\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_ADC_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_ADCRST\fP)"

.SS "#define __HAL_RCC_ADC_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_ADCRST\fP)"

.SS "#define __HAL_RCC_APB2_FORCE_RESET()   \fBWRITE_REG\fP(\fBRCC\fP\->APBRSTR2, 0xFFFFFFFFU)"

.SS "#define __HAL_RCC_APB2_RELEASE_RESET()   \fBWRITE_REG\fP(\fBRCC\fP\->APBRSTR2, 0x00U)"

.SS "#define __HAL_RCC_SPI1_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SPI1RST\fP)"

.SS "#define __HAL_RCC_SPI1_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SPI1RST\fP)"

.SS "#define __HAL_RCC_SYSCFG_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SYSCFGRST\fP)"

.SS "#define __HAL_RCC_SYSCFG_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_SYSCFGRST\fP)"

.SS "#define __HAL_RCC_TIM14_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM14RST\fP)"

.SS "#define __HAL_RCC_TIM14_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM14RST\fP)"

.SS "#define __HAL_RCC_TIM16_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM16RST\fP)"

.SS "#define __HAL_RCC_TIM16_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM16RST\fP)"

.SS "#define __HAL_RCC_TIM17_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM17RST\fP)"

.SS "#define __HAL_RCC_TIM17_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM17RST\fP)"

.SS "#define __HAL_RCC_TIM1_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM1RST\fP)"

.SS "#define __HAL_RCC_TIM1_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_TIM1RST\fP)"

.SS "#define __HAL_RCC_USART1_FORCE_RESET()   \fBSET_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_USART1RST\fP)"

.SS "#define __HAL_RCC_USART1_RELEASE_RESET()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBRSTR2, \fBRCC_APBRSTR2_USART1RST\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
