.TH "RCC_PLLR_Clock_Divider" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PLLR_Clock_Divider \- PLLR Clock Divider
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_PLLR_DIV2\fP   \fBRCC_PLLCFGR_PLLR_0\fP"
.br
.ti -1c
.RI "#define \fBRCC_PLLR_DIV3\fP   \fBRCC_PLLCFGR_PLLR_1\fP"
.br
.ti -1c
.RI "#define \fBRCC_PLLR_DIV4\fP   (\fBRCC_PLLCFGR_PLLR_1\fP | \fBRCC_PLLCFGR_PLLR_0\fP)"
.br
.ti -1c
.RI "#define \fBRCC_PLLR_DIV5\fP   \fBRCC_PLLCFGR_PLLR_2\fP"
.br
.ti -1c
.RI "#define \fBRCC_PLLR_DIV6\fP   (\fBRCC_PLLCFGR_PLLR_2\fP | \fBRCC_PLLCFGR_PLLR_0\fP)"
.br
.ti -1c
.RI "#define \fBRCC_PLLR_DIV7\fP   (\fBRCC_PLLCFGR_PLLR_2\fP | \fBRCC_PLLCFGR_PLLR_1\fP)"
.br
.ti -1c
.RI "#define \fBRCC_PLLR_DIV8\fP   (\fBRCC_PLLCFGR_PLLR_2\fP | \fBRCC_PLLCFGR_PLLR_1\fP | \fBRCC_PLLCFGR_PLLR_0\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_PLLR_DIV2   \fBRCC_PLLCFGR_PLLR_0\fP"
PLLR division factor = 2 
.SS "#define RCC_PLLR_DIV3   \fBRCC_PLLCFGR_PLLR_1\fP"
PLLR division factor = 3 
.SS "#define RCC_PLLR_DIV4   (\fBRCC_PLLCFGR_PLLR_1\fP | \fBRCC_PLLCFGR_PLLR_0\fP)"
PLLR division factor = 4 
.SS "#define RCC_PLLR_DIV5   \fBRCC_PLLCFGR_PLLR_2\fP"
PLLR division factor = 5 
.SS "#define RCC_PLLR_DIV6   (\fBRCC_PLLCFGR_PLLR_2\fP | \fBRCC_PLLCFGR_PLLR_0\fP)"
PLLR division factor = 6 
.SS "#define RCC_PLLR_DIV7   (\fBRCC_PLLCFGR_PLLR_2\fP | \fBRCC_PLLCFGR_PLLR_1\fP)"
PLLR division factor = 7 
.SS "#define RCC_PLLR_DIV8   (\fBRCC_PLLCFGR_PLLR_2\fP | \fBRCC_PLLCFGR_PLLR_1\fP | \fBRCC_PLLCFGR_PLLR_0\fP)"
PLLR division factor = 8 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
