.TH "RCC_Timeout_Value" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Timeout_Value \- Timeout Values
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_DBP_TIMEOUT_VALUE\fP   2U                   /* 2 ms (minimum Tick + 1)  */"
.br
.ti -1c
.RI "#define \fBRCC_LSE_TIMEOUT_VALUE\fP   \fBLSE_STARTUP_TIMEOUT\fP  /* LSE timeout in ms        */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_DBP_TIMEOUT_VALUE   2U                   /* 2 ms (minimum Tick + 1)  */"

.SS "#define RCC_LSE_TIMEOUT_VALUE   \fBLSE_STARTUP_TIMEOUT\fP  /* LSE timeout in ms        */"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
