.TH "RCC_PLL_Clock_Source" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PLL_Clock_Source \- PLL Clock Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_PLLSOURCE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_PLLSOURCE_HSI\fP   \fBRCC_PLLCFGR_PLLSRC_HSI\fP"
.br
.ti -1c
.RI "#define \fBRCC_PLLSOURCE_HSE\fP   \fBRCC_PLLCFGR_PLLSRC_HSE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_PLLSOURCE_HSE   \fBRCC_PLLCFGR_PLLSRC_HSE\fP"
HSE clock selected as PLL entry clock source 
.SS "#define RCC_PLLSOURCE_HSI   \fBRCC_PLLCFGR_PLLSRC_HSI\fP"
HSI clock selected as PLL entry clock source 
.SS "#define RCC_PLLSOURCE_NONE   0x00000000U"
No clock selected as PLL entry clock source 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
