.TH "RCC_Exported_Macros" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Exported_Macros \- RCC Exported Macros
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAHB Peripheral Clock Enable Disable\fP"
.br
.RI "Enable or disable the AHB peripheral clock\&. "
.ti -1c
.RI "\fBIOPORT Clock Enable Disable\fP"
.br
.RI "Enable or disable the IO Ports clock\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Clock Enable Disable\fP"
.br
.RI "Enable or disable the APB1 peripheral clock\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Clock Enable Disable\fP"
.br
.RI "Enable or disable the APB2 peripheral clock\&. "
.ti -1c
.RI "\fBAHB Peripheral Clock Enabled or Disabled Status\fP"
.br
.RI "Check whether the AHB peripheral clock is enabled or not\&. "
.ti -1c
.RI "\fBIOPORT Clock Enabled or Disabled Status\fP"
.br
.RI "Check whether the IO Port clock is enabled or not\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Clock Enabled or Disabled Status\fP"
.br
.RI "Check whether the APB1 peripheral clock is enabled or not\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Clock Enabled or Disabled Status\fP"
.br
.RI "Check whether the APB2 peripheral clock is enabled or not\&. "
.ti -1c
.RI "\fBAHB Peripheral Force Release Reset\fP"
.br
.RI "Force or release AHB1 peripheral reset\&. "
.ti -1c
.RI "\fBIOPORT Force Release Reset\fP"
.br
.RI "Force or release IO Port reset\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Force Release Reset\fP"
.br
.RI "Force or release APB1 peripheral reset\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Force Release Reset\fP"
.br
.RI "Force or release APB2 peripheral reset\&. "
.ti -1c
.RI "\fBAHB Peripherals Clock Sleep Enable Disable\fP"
.br
.RI "Enable or disable the AHB peripherals clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBIOPORT Clock Sleep Enable Disable\fP"
.br
.RI "Enable or disable the IOPORT clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Clock Sleep Enable Disable\fP"
.br
.RI "Enable or disable the APB1 peripheral clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Clock Sleep Enable Disable\fP"
.br
.RI "Enable or disable the APB2 peripheral clock during Low Power (Sleep) mode\&. "
.ti -1c
.RI "\fBAHB Peripheral Clock Sleep Enabled or Disabled Status\fP"
.br
.RI "Check whether the AHB peripheral clock during Low Power (Sleep) mode is enabled or not\&. "
.ti -1c
.RI "\fBIOPORT Clock Sleep Enabled or Disabled Status\fP"
.br
.RI "Check whether the IOPORT clock during Low Power (Sleep) mode is enabled or not\&. "
.ti -1c
.RI "\fBAPB1 Peripheral Clock Sleep Enabled or Disabled Status\fP"
.br
.RI "Check whether the APB1 peripheral clock during Low Power (Sleep) mode is enabled or not\&. "
.ti -1c
.RI "\fBAPB2 Peripheral Clock Sleep Enabled or Disabled Status\fP"
.br
.RI "Check whether the APB2 peripheral clock during Low Power (Sleep) mode is enabled or not\&. "
.ti -1c
.RI "\fBRCC Backup Domain Reset\fP"
.br
.ti -1c
.RI "\fBRCC RTC Clock Configuration\fP"
.br
.ti -1c
.RI "\fBRCC Clock Configuration\fP"
.br
.ti -1c
.RI "\fBFlags Interrupts Management\fP"
.br
.RI "macros to manage the specified RCC Flags and interrupts\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
