.TH "RCC_APB2_Clock_Sleep_Enable_Disable" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB2_Clock_Sleep_Enable_Disable \- APB2 Peripheral Clock Sleep Enable Disable
.PP
 \- Enable or disable the APB2 peripheral clock during Low Power (Sleep) mode\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SYSCFGSMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM1SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SPI1SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_USART1SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM14_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM14SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM16_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM16SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM17_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM17SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC_CLK_SLEEP_ENABLE\fP()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_ADCSMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SYSCFGSMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM1SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SPI1SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_USART1SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM14_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM14SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM16_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM16SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM17_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM17SMEN\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC_CLK_SLEEP_DISABLE\fP()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_ADCSMEN\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enable or disable the APB2 peripheral clock during Low Power (Sleep) mode\&. 


.PP
\fBNote\fP
.RS 4
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption\&. 
.PP
After wakeup from SLEEP mode, the peripheral clock is enabled again\&. 
.PP
By default, all peripheral clocks are enabled during SLEEP mode\&. 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_ADC_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_ADCSMEN\fP)"

.SS "#define __HAL_RCC_ADC_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_ADCSMEN\fP)"

.SS "#define __HAL_RCC_SPI1_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SPI1SMEN\fP)"

.SS "#define __HAL_RCC_SPI1_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SPI1SMEN\fP)"

.SS "#define __HAL_RCC_SYSCFG_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SYSCFGSMEN\fP)"

.SS "#define __HAL_RCC_SYSCFG_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_SYSCFGSMEN\fP)"

.SS "#define __HAL_RCC_TIM14_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM14SMEN\fP)"

.SS "#define __HAL_RCC_TIM14_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM14SMEN\fP)"

.SS "#define __HAL_RCC_TIM16_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM16SMEN\fP)"

.SS "#define __HAL_RCC_TIM16_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM16SMEN\fP)"

.SS "#define __HAL_RCC_TIM17_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM17SMEN\fP)"

.SS "#define __HAL_RCC_TIM17_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM17SMEN\fP)"

.SS "#define __HAL_RCC_TIM1_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM1SMEN\fP)"

.SS "#define __HAL_RCC_TIM1_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_TIM1SMEN\fP)"

.SS "#define __HAL_RCC_USART1_CLK_SLEEP_DISABLE()   \fBCLEAR_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_USART1SMEN\fP)"

.SS "#define __HAL_RCC_USART1_CLK_SLEEP_ENABLE()   \fBSET_BIT\fP(\fBRCC\fP\->APBSMENR2 , \fBRCC_APBSMENR2_USART1SMEN\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
