.TH "RCC_HSE_Config" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_HSE_Config \- HSE Config
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_HSE_OFF\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_HSE_ON\fP   \fBRCC_CR_HSEON\fP"
.br
.ti -1c
.RI "#define \fBRCC_HSE_BYPASS\fP   (\fBRCC_CR_HSEBYP\fP | \fBRCC_CR_HSEON\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_HSE_BYPASS   (\fBRCC_CR_HSEBYP\fP | \fBRCC_CR_HSEON\fP)"
External clock source for HSE clock 
.SS "#define RCC_HSE_OFF   0x00000000U"
HSE clock deactivation 
.SS "#define RCC_HSE_ON   \fBRCC_CR_HSEON\fP"
HSE clock activation 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
