.TH "RCCEx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx \- RCCEx
.PP
 \- RCC Extended HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBRCCEx Exported Types\fP"
.br
.ti -1c
.RI "\fBRCCEx Exported Constants\fP"
.br
.ti -1c
.RI "\fBRCCEx Exported Macros\fP"
.br
.ti -1c
.RI "\fBRCCEx Private Macros\fP"
.br
.ti -1c
.RI "\fBRCCEx_Exported_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RCC Extended HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
