.TH "RCCEx_Exported_Functions_Group2" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_Exported_Functions_Group2 \- RCCEx_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_RCCEx_EnableLSCO\fP (uint32_t LSCOSource)"
.br
.ti -1c
.RI "void \fBHAL_RCCEx_DisableLSCO\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_RCCEx_DisableLSCO (void)"

.SS "void HAL_RCCEx_EnableLSCO (uint32_t LSCOSource)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
