.TH "RCCEx_Periph_Clock_Selection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_Periph_Clock_Selection \- Periph Clock Selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_PERIPHCLK_USART1\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRCC_PERIPHCLK_I2C1\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBRCC_PERIPHCLK_I2S1\fP   0x00000800U"
.br
.ti -1c
.RI "#define \fBRCC_PERIPHCLK_ADC\fP   0x00004000U"
.br
.ti -1c
.RI "#define \fBRCC_PERIPHCLK_RTC\fP   0x00020000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_PERIPHCLK_ADC   0x00004000U"

.SS "#define RCC_PERIPHCLK_I2C1   0x00000020U"

.SS "#define RCC_PERIPHCLK_I2S1   0x00000800U"

.SS "#define RCC_PERIPHCLK_RTC   0x00020000U"

.SS "#define RCC_PERIPHCLK_USART1   0x00000001U"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
