.TH "RCCEx_LSCO_Clock_Source" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_LSCO_Clock_Source \- Low Speed Clock Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_LSCOSOURCE_LSI\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_LSCOSOURCE_LSE\fP   \fBRCC_BDCR_LSCOSEL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_LSCOSOURCE_LSE   \fBRCC_BDCR_LSCOSEL\fP"
LSE selection for low speed clock output 
.SS "#define RCC_LSCOSOURCE_LSI   0x00000000U"
LSI selection for low speed clock output 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
