.TH "Core/Src/spi.c" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/spi.c \- This file provides code for the configuration of the SPI instances\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'spi\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_SPI1_Init\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SPI_MspInit\fP (\fBSPI_HandleTypeDef\fP *spiHandle)"
.br
.ti -1c
.RI "void \fBHAL_SPI_MspDeInit\fP (\fBSPI_HandleTypeDef\fP *spiHandle)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSPI_HandleTypeDef\fP \fBhspi1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file provides code for the configuration of the SPI instances\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2023 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Function Documentation"
.PP 
.SS "void MX_SPI1_Init (void)"

.SH "Variable Documentation"
.PP 
.SS "\fBSPI_HandleTypeDef\fP hspi1"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
