.TH "Core/Inc/spi.h" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc/spi.h \- This file contains all the function prototypes for the \fBspi\&.c\fP file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMX_SPI1_Init\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSPI_HandleTypeDef\fP \fBhspi1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains all the function prototypes for the \fBspi\&.c\fP file\&. 


.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2023 STMicroelectronics\&. All rights reserved\&.
.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Function Documentation"
.PP 
.SS "void MX_SPI1_Init (void)"

.SH "Variable Documentation"
.PP 
.SS "\fBSPI_HandleTypeDef\fP hspi1\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
