.TH "SPI_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Exported_Constants \- SPI Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSPI Error Code\fP"
.br
.ti -1c
.RI "\fBSPI Mode\fP"
.br
.ti -1c
.RI "\fBSPI Direction Mode\fP"
.br
.ti -1c
.RI "\fBSPI Data Size\fP"
.br
.ti -1c
.RI "\fBSPI Clock Polarity\fP"
.br
.ti -1c
.RI "\fBSPI Clock Phase\fP"
.br
.ti -1c
.RI "\fBSPI Slave Select Management\fP"
.br
.ti -1c
.RI "\fBSPI NSS Pulse Mode\fP"
.br
.ti -1c
.RI "\fBSPI BaudRate Prescaler\fP"
.br
.ti -1c
.RI "\fBSPI MSB LSB Transmission\fP"
.br
.ti -1c
.RI "\fBSPI TI Mode\fP"
.br
.ti -1c
.RI "\fBSPI CRC Calculation\fP"
.br
.ti -1c
.RI "\fBSPI CRC Length\fP"
.br
.ti -1c
.RI "\fBSPI FIFO Reception Threshold\fP"
.br
.ti -1c
.RI "\fBSPI Interrupt Definition\fP"
.br
.ti -1c
.RI "\fBSPI Flags Definition\fP"
.br
.ti -1c
.RI "\fBSPI Transmission FIFO Status Level\fP"
.br
.ti -1c
.RI "\fBSPI Reception FIFO Status Level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
