.TH "SPI_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Exported_Functions_Group1 \- SPI_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SPI_Init\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SPI_DeInit\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.ti -1c
.RI "void \fBHAL_SPI_MspInit\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.ti -1c
.RI "void \fBHAL_SPI_MspDeInit\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_SPI_DeInit (\fBSPI_HandleTypeDef\fP * hspi)"

.SS "\fBHAL_StatusTypeDef\fP HAL_SPI_Init (\fBSPI_HandleTypeDef\fP * hspi)"

.SS "void HAL_SPI_MspDeInit (\fBSPI_HandleTypeDef\fP * hspi)"
SPI1 GPIO Configuration PB3 ------> SPI1_SCK PB4 ------> SPI1_MISO PB5 ------> SPI1_MOSI
.SS "void HAL_SPI_MspInit (\fBSPI_HandleTypeDef\fP * hspi)"
SPI1 GPIO Configuration PB3 ------> SPI1_SCK PB4 ------> SPI1_MISO PB5 ------> SPI1_MOSI
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
