.TH "SPI_CRC_length" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_CRC_length \- SPI CRC Length
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_CRC_LENGTH_DATASIZE\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_CRC_LENGTH_8BIT\fP   (0x00000001U)"
.br
.ti -1c
.RI "#define \fBSPI_CRC_LENGTH_16BIT\fP   (0x00000002U)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This parameter can be one of the following values: SPI_CRC_LENGTH_DATASIZE: aligned with the data size SPI_CRC_LENGTH_8BIT : CRC 8bit SPI_CRC_LENGTH_16BIT : CRC 16bit 
.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_CRC_LENGTH_16BIT   (0x00000002U)"

.SS "#define SPI_CRC_LENGTH_8BIT   (0x00000001U)"

.SS "#define SPI_CRC_LENGTH_DATASIZE   (0x00000000U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
