.TH "SPI_BaudRate_Prescaler" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_BaudRate_Prescaler \- SPI BaudRate Prescaler
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_2\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_4\fP   (\fBSPI_CR1_BR_0\fP)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_8\fP   (\fBSPI_CR1_BR_1\fP)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_16\fP   (\fBSPI_CR1_BR_1\fP | \fBSPI_CR1_BR_0\fP)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_32\fP   (\fBSPI_CR1_BR_2\fP)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_64\fP   (\fBSPI_CR1_BR_2\fP | \fBSPI_CR1_BR_0\fP)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_128\fP   (\fBSPI_CR1_BR_2\fP | \fBSPI_CR1_BR_1\fP)"
.br
.ti -1c
.RI "#define \fBSPI_BAUDRATEPRESCALER_256\fP   (\fBSPI_CR1_BR_2\fP | \fBSPI_CR1_BR_1\fP | \fBSPI_CR1_BR_0\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_BAUDRATEPRESCALER_128   (\fBSPI_CR1_BR_2\fP | \fBSPI_CR1_BR_1\fP)"

.SS "#define SPI_BAUDRATEPRESCALER_16   (\fBSPI_CR1_BR_1\fP | \fBSPI_CR1_BR_0\fP)"

.SS "#define SPI_BAUDRATEPRESCALER_2   (0x00000000U)"

.SS "#define SPI_BAUDRATEPRESCALER_256   (\fBSPI_CR1_BR_2\fP | \fBSPI_CR1_BR_1\fP | \fBSPI_CR1_BR_0\fP)"

.SS "#define SPI_BAUDRATEPRESCALER_32   (\fBSPI_CR1_BR_2\fP)"

.SS "#define SPI_BAUDRATEPRESCALER_4   (\fBSPI_CR1_BR_0\fP)"

.SS "#define SPI_BAUDRATEPRESCALER_64   (\fBSPI_CR1_BR_2\fP | \fBSPI_CR1_BR_0\fP)"

.SS "#define SPI_BAUDRATEPRESCALER_8   (\fBSPI_CR1_BR_1\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
