.TH "SPI_Slave_Select_management" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Slave_Select_management \- SPI Slave Select Management
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_NSS_SOFT\fP   \fBSPI_CR1_SSM\fP"
.br
.ti -1c
.RI "#define \fBSPI_NSS_HARD_INPUT\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_NSS_HARD_OUTPUT\fP   (\fBSPI_CR2_SSOE\fP << 16U)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_NSS_HARD_INPUT   (0x00000000U)"

.SS "#define SPI_NSS_HARD_OUTPUT   (\fBSPI_CR2_SSOE\fP << 16U)"

.SS "#define SPI_NSS_SOFT   \fBSPI_CR1_SSM\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
