.TH "SPI_Clock_Polarity" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Clock_Polarity \- SPI Clock Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_POLARITY_LOW\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_POLARITY_HIGH\fP   \fBSPI_CR1_CPOL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_POLARITY_HIGH   \fBSPI_CR1_CPOL\fP"

.SS "#define SPI_POLARITY_LOW   (0x00000000U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
