.TH "SPI_Exported_Functions_Group3" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Exported_Functions_Group3 \- SPI_Exported_Functions_Group3
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_SPI_StateTypeDef\fP \fBHAL_SPI_GetState\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SPI_GetError\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "uint32_t HAL_SPI_GetError (\fBSPI_HandleTypeDef\fP * hspi)"

.SS "\fBHAL_SPI_StateTypeDef\fP HAL_SPI_GetState (\fBSPI_HandleTypeDef\fP * hspi)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
