.TH "SPI_reception_fifo_status_level" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_reception_fifo_status_level \- SPI Reception FIFO Status Level
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_FRLVL_EMPTY\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_FRLVL_QUARTER_FULL\fP   (0x00000200U)"
.br
.ti -1c
.RI "#define \fBSPI_FRLVL_HALF_FULL\fP   (0x00000400U)"
.br
.ti -1c
.RI "#define \fBSPI_FRLVL_FULL\fP   (0x00000600U)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_FRLVL_EMPTY   (0x00000000U)"

.SS "#define SPI_FRLVL_FULL   (0x00000600U)"

.SS "#define SPI_FRLVL_HALF_FULL   (0x00000400U)"

.SS "#define SPI_FRLVL_QUARTER_FULL   (0x00000200U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
