.TH "SPI_Exported_Functions" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Exported_Functions \- SPI_Exported_Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSPI_Exported_Functions_Group1\fP"
.br
.ti -1c
.RI "\fBSPI_Exported_Functions_Group2\fP"
.br
.ti -1c
.RI "\fBSPI_Exported_Functions_Group3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
