.TH "SPI_Data_Size" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Data_Size \- SPI Data Size
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_DATASIZE_4BIT\fP   (0x00000300U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_5BIT\fP   (0x00000400U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_6BIT\fP   (0x00000500U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_7BIT\fP   (0x00000600U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_8BIT\fP   (0x00000700U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_9BIT\fP   (0x00000800U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_10BIT\fP   (0x00000900U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_11BIT\fP   (0x00000A00U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_12BIT\fP   (0x00000B00U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_13BIT\fP   (0x00000C00U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_14BIT\fP   (0x00000D00U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_15BIT\fP   (0x00000E00U)"
.br
.ti -1c
.RI "#define \fBSPI_DATASIZE_16BIT\fP   (0x00000F00U)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_DATASIZE_10BIT   (0x00000900U)"

.SS "#define SPI_DATASIZE_11BIT   (0x00000A00U)"

.SS "#define SPI_DATASIZE_12BIT   (0x00000B00U)"

.SS "#define SPI_DATASIZE_13BIT   (0x00000C00U)"

.SS "#define SPI_DATASIZE_14BIT   (0x00000D00U)"

.SS "#define SPI_DATASIZE_15BIT   (0x00000E00U)"

.SS "#define SPI_DATASIZE_16BIT   (0x00000F00U)"

.SS "#define SPI_DATASIZE_4BIT   (0x00000300U)"

.SS "#define SPI_DATASIZE_5BIT   (0x00000400U)"

.SS "#define SPI_DATASIZE_6BIT   (0x00000500U)"

.SS "#define SPI_DATASIZE_7BIT   (0x00000600U)"

.SS "#define SPI_DATASIZE_8BIT   (0x00000700U)"

.SS "#define SPI_DATASIZE_9BIT   (0x00000800U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
