.TH "SPI_Interrupt_definition" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Interrupt_definition \- SPI Interrupt Definition
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_IT_TXE\fP   \fBSPI_CR2_TXEIE\fP"
.br
.ti -1c
.RI "#define \fBSPI_IT_RXNE\fP   \fBSPI_CR2_RXNEIE\fP"
.br
.ti -1c
.RI "#define \fBSPI_IT_ERR\fP   \fBSPI_CR2_ERRIE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_IT_ERR   \fBSPI_CR2_ERRIE\fP"

.SS "#define SPI_IT_RXNE   \fBSPI_CR2_RXNEIE\fP"

.SS "#define SPI_IT_TXE   \fBSPI_CR2_TXEIE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
