.TH "SPI_CRC_Calculation" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_CRC_Calculation \- SPI CRC Calculation
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_DISABLE\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_ENABLE\fP   \fBSPI_CR1_CRCEN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_CRCCALCULATION_DISABLE   (0x00000000U)"

.SS "#define SPI_CRCCALCULATION_ENABLE   \fBSPI_CR1_CRCEN\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
