.TH "SPIEx_Exported_Functions_Group1" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPIEx_Exported_Functions_Group1 \- SPIEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SPIEx_FlushRxFifo\fP (\fBSPI_HandleTypeDef\fP *hspi)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_SPIEx_FlushRxFifo (\fBSPI_HandleTypeDef\fP * hspi)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
