.TH "STM32G0xx_System_Exported_types" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32G0xx_System_Exported_types \- STM32G0xx_System_Exported_types
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP"
.br
.ti -1c
.RI "const uint32_t \fBAHBPrescTable\fP [16]"
.br
.ti -1c
.RI "const uint32_t \fBAPBPrescTable\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "const uint32_t AHBPrescTable[16]\fC [extern]\fP"
AHB prescalers table values 
.SS "const uint32_t APBPrescTable[8]\fC [extern]\fP"
APB prescalers table values 
.SS "uint32_t SystemCoreClock\fC [extern]\fP"
System Clock Frequency (Core Clock) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
