.TH "STM32G0xx_System_Private_Variables" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32G0xx_System_Private_Variables \- STM32G0xx_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 16000000UL"
.br
.ti -1c
.RI "const uint32_t \fBAHBPrescTable\fP [16UL] = {0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 1UL, 2UL, 3UL, 4UL, 6UL, 7UL, 8UL, 9UL}"
.br
.ti -1c
.RI "const uint32_t \fBAPBPrescTable\fP [8UL] = {0UL, 0UL, 0UL, 0UL, 1UL, 2UL, 3UL, 4UL}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "const uint32_t AHBPrescTable[16UL] = {0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 1UL, 2UL, 3UL, 4UL, 6UL, 7UL, 8UL, 9UL}"
AHB prescalers table values 
.SS "const uint32_t APBPrescTable[8UL] = {0UL, 0UL, 0UL, 0UL, 1UL, 2UL, 3UL, 4UL}"
APB prescalers table values 
.SS "uint32_t SystemCoreClock = 16000000UL"
System Clock Frequency (Core Clock) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
