.TH "STM32G0xx_HAL_Driver" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32G0xx_HAL_Driver \- STM32G0xx_HAL_Driver
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBHAL\fP"
.br
.RI "HAL module driver\&. "
.ti -1c
.RI "\fBCORTEX\fP"
.br
.RI "CORTEX HAL module driver\&. "
.ti -1c
.RI "\fBEXTI\fP"
.br
.RI "EXTI HAL module driver\&. "
.ti -1c
.RI "\fBGPIO\fP"
.br
.RI "GPIO HAL module driver\&. "
.ti -1c
.RI "\fBGPIOEx\fP"
.br
.RI "GPIO Extended HAL module driver\&. "
.ti -1c
.RI "\fBPWR\fP"
.br
.RI "PWR HAL module driver\&. "
.ti -1c
.RI "\fBPWREx\fP"
.br
.RI "PWR Extended HAL module driver\&. "
.ti -1c
.RI "\fBDMA\fP"
.br
.RI "DMA HAL module driver\&. "
.ti -1c
.RI "\fBDMAEx\fP"
.br
.RI "DMA Extended HAL module driver\&. "
.ti -1c
.RI "\fBFLASH\fP"
.br
.RI "FLASH HAL module driver\&. "
.ti -1c
.RI "\fBFLASHEx\fP"
.br
.RI "FLASH Extended HAL module driver\&. "
.ti -1c
.RI "\fBRCC\fP"
.br
.RI "RCC HAL module driver\&. "
.ti -1c
.RI "\fBRCCEx\fP"
.br
.RI "RCC Extended HAL module driver\&. "
.ti -1c
.RI "\fBSPI\fP"
.br
.RI "SPI HAL module driver\&. "
.ti -1c
.RI "\fBSPIEx\fP"
.br
.RI "SPI Extended HAL module driver\&. "
.ti -1c
.RI "\fBTIM\fP"
.br
.RI "TIM HAL module driver\&. "
.ti -1c
.RI "\fBTIMEx\fP"
.br
.RI "TIM Extended HAL module driver\&. "
.ti -1c
.RI "\fBUART\fP"
.br
.RI "HAL UART module driver\&. "
.ti -1c
.RI "\fBUARTEx\fP"
.br
.RI "UART Extended HAL module driver\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
