.TH "SYSCFG_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSCFG_Exported_Constants \- SYSCFG Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBBoot Mode\fP"
.br
.ti -1c
.RI "\fBBreak\fP"
.br
.ti -1c
.RI "\fBPin remapping\fP"
.br
.ti -1c
.RI "\fBIR Modulation Envelope signal selection\fP"
.br
.ti -1c
.RI "\fBIR output polarity selection\fP"
.br
.ti -1c
.RI "\fBFast mode Plus on GPIO\fP"
.br
.ti -1c
.RI "\fBFast mode Plus driving capability activation for I2Cx\fP"
.br
.ti -1c
.RI "\fBHAL ISR Wrapper\fP"
.br
.RI "ISR Wrapper\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
