.TH "SYSCFG_FastModePlus_I2Cx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSCFG_FastModePlus_I2Cx \- Fast mode Plus driving capability activation for I2Cx
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_I2C1\fP   \fBSYSCFG_CFGR1_I2C1_FMP\fP"
.br
.RI "Fast mode Plus driving capability on a specific GPIO\&. "
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_I2C2\fP   \fBSYSCFG_CFGR1_I2C2_FMP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SYSCFG_FASTMODEPLUS_I2C1   \fBSYSCFG_CFGR1_I2C1_FMP\fP"

.PP
Fast mode Plus driving capability on a specific GPIO\&. Enable Fast mode Plus on I2C1 
.SS "#define SYSCFG_FASTMODEPLUS_I2C2   \fBSYSCFG_CFGR1_I2C2_FMP\fP"
Enable Fast mode Plus on I2C2 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
