.TH "SYSCFG_FastModePlus_GPIO" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSCFG_FastModePlus_GPIO \- Fast mode Plus on GPIO
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_PB6\fP   \fBSYSCFG_CFGR1_I2C_PB6_FMP\fP"
.br
.RI "Fast mode Plus driving capability on a specific GPIO\&. "
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_PB7\fP   \fBSYSCFG_CFGR1_I2C_PB7_FMP\fP"
.br
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_PB8\fP   \fBSYSCFG_CFGR1_I2C_PB8_FMP\fP"
.br
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_PB9\fP   \fBSYSCFG_CFGR1_I2C_PB9_FMP\fP"
.br
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_PA9\fP   \fBSYSCFG_CFGR1_I2C_PA9_FMP\fP"
.br
.ti -1c
.RI "#define \fBSYSCFG_FASTMODEPLUS_PA10\fP   \fBSYSCFG_CFGR1_I2C_PA10_FMP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SYSCFG_FASTMODEPLUS_PA10   \fBSYSCFG_CFGR1_I2C_PA10_FMP\fP"
Enable Fast mode Plus on PA10 
.SS "#define SYSCFG_FASTMODEPLUS_PA9   \fBSYSCFG_CFGR1_I2C_PA9_FMP\fP"
Enable Fast mode Plus on PA9 
.SS "#define SYSCFG_FASTMODEPLUS_PB6   \fBSYSCFG_CFGR1_I2C_PB6_FMP\fP"

.PP
Fast mode Plus driving capability on a specific GPIO\&. Enable Fast mode Plus on PB6 
.SS "#define SYSCFG_FASTMODEPLUS_PB7   \fBSYSCFG_CFGR1_I2C_PB7_FMP\fP"
Enable Fast mode Plus on PB7 
.SS "#define SYSCFG_FASTMODEPLUS_PB8   \fBSYSCFG_CFGR1_I2C_PB8_FMP\fP"
Enable Fast mode Plus on PB8 
.SS "#define SYSCFG_FASTMODEPLUS_PB9   \fBSYSCFG_CFGR1_I2C_PB9_FMP\fP"
Enable Fast mode Plus on PB9 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
