.TH "TIM_Output_Fast_State" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Fast_State \- TIM Output Fast State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCFAST_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_OCFAST_ENABLE\fP   \fBTIM_CCMR1_OC1FE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_OCFAST_DISABLE   0x00000000U"
Output Compare fast disable 
.SS "#define TIM_OCFAST_ENABLE   \fBTIM_CCMR1_OC1FE\fP"
Output Compare fast enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
