.TH "TIM_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_TypeDef \- TIM\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSMCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCMR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCMR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPSC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBARR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCMR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAF1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAF2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTISEL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::AF1"
TIM alternate function register 1, Address offset: 0x60 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::AF2"
TIM alternate function register 2, Address offset: 0x64 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::ARR"
TIM auto-reload register, Address offset: 0x2C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::BDTR"
TIM break and dead-time register, Address offset: 0x44 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCER"
TIM capture/compare enable register, Address offset: 0x20 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCMR1"
TIM capture/compare mode register 1, Address offset: 0x18 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCMR2"
TIM capture/compare mode register 2, Address offset: 0x1C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCMR3"
TIM capture/compare mode register 3, Address offset: 0x54 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR1"
TIM capture/compare register 1, Address offset: 0x34 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR2"
TIM capture/compare register 2, Address offset: 0x38 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR3"
TIM capture/compare register 3, Address offset: 0x3C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR4"
TIM capture/compare register 4, Address offset: 0x40 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR5"
TIM capture/compare register5, Address offset: 0x58 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR6"
TIM capture/compare register6, Address offset: 0x5C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CNT"
TIM counter register, Address offset: 0x24 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CR1"
TIM control register 1, Address offset: 0x00 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CR2"
TIM control register 2, Address offset: 0x04 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::DCR"
TIM DMA control register, Address offset: 0x48 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::DIER"
TIM DMA/interrupt enable register, Address offset: 0x0C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::DMAR"
TIM DMA address for full transfer, Address offset: 0x4C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::EGR"
TIM event generation register, Address offset: 0x14 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::OR1"
TIM option register, Address offset: 0x50 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::PSC"
TIM prescaler register, Address offset: 0x28 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::RCR"
TIM repetition counter register, Address offset: 0x30 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::SMCR"
TIM slave mode control register, Address offset: 0x08 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::SR"
TIM status register, Address offset: 0x10 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::TISEL"
TIM Input Selection register, Address offset: 0x68 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
