.TH "TIM_CC_DMA_Request" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_CC_DMA_Request \- CCx DMA request selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CCDMAREQUEST_CC\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_CCDMAREQUEST_UPDATE\fP   \fBTIM_CR2_CCDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CCDMAREQUEST_CC   0x00000000U"
CCx DMA request sent when capture or compare match event occurs 
.SS "#define TIM_CCDMAREQUEST_UPDATE   \fBTIM_CR2_CCDS\fP"
CCx DMA requests sent when update event occurs 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
