.TH "TIM_Break2_Polarity" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Break2_Polarity \- TIM Break Input 2 Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAK2POLARITY_LOW\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_BREAK2POLARITY_HIGH\fP   \fBTIM_BDTR_BK2P\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAK2POLARITY_HIGH   \fBTIM_BDTR_BK2P\fP"
Break input BRK2 is active high 
.br
 
.SS "#define TIM_BREAK2POLARITY_LOW   0x00000000U"
Break input BRK2 is active low 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
