.TH "TIM_Break2_Input_enable_disable" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Break2_Input_enable_disable \- TIM Break input 2 Enable
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAK2_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_BREAK2_ENABLE\fP   \fBTIM_BDTR_BK2E\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAK2_DISABLE   0x00000000U"
Break input BRK2 is disabled 
.br
 
.SS "#define TIM_BREAK2_ENABLE   \fBTIM_BDTR_BK2E\fP"
Break input BRK2 is enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
