.TH "TIM_Exported_Functions_Group10" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group10 \- TIM Peripheral State functions
.PP
 \- Peripheral State functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_Base_GetState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_OC_GetState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_PWM_GetState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_IC_GetState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_OnePulse_GetState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_Encoder_GetState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_ActiveChannel\fP \fBHAL_TIM_GetActiveChannel\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_ChannelStateTypeDef\fP \fBHAL_TIM_GetChannelState\fP (const \fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_TIM_DMABurstStateTypeDef\fP \fBHAL_TIM_DMABurstState\fP (const \fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Peripheral State functions\&. 


.SH "Function Documentation"
.PP 
.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_Base_GetState (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_DMABurstStateTypeDef\fP HAL_TIM_DMABurstState (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_Encoder_GetState (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_ActiveChannel\fP HAL_TIM_GetActiveChannel (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_ChannelStateTypeDef\fP HAL_TIM_GetChannelState (const \fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_IC_GetState (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_OC_GetState (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_OnePulse_GetState (const \fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_PWM_GetState (const \fBTIM_HandleTypeDef\fP * htim)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
