.TH "TIM_TI1_Selection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_TI1_Selection \- TIM TI1 Input Selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_TI1SELECTION_CH1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TI1SELECTION_XORCOMBINATION\fP   \fBTIM_CR2_TI1S\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_TI1SELECTION_CH1   0x00000000U"
The TIMx_CH1 pin is connected to TI1 input 
.SS "#define TIM_TI1SELECTION_XORCOMBINATION   \fBTIM_CR2_TI1S\fP"
The TIMx_CH1, CH2 and CH3 pins are connected to the TI1 input (XOR combination) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
