.TH "TIM_Output_Compare_N_State" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_N_State \- TIM Complementary Output Compare State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OUTPUTNSTATE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_OUTPUTNSTATE_ENABLE\fP   \fBTIM_CCER_CC1NE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_OUTPUTNSTATE_DISABLE   0x00000000U"
OCxN is disabled 
.br
 
.SS "#define TIM_OUTPUTNSTATE_ENABLE   \fBTIM_CCER_CC1NE\fP"
OCxN is enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
