.TH "TIM_Update_Interrupt_Flag_Remap" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Update_Interrupt_Flag_Remap \- TIM Update Interrupt Flag Remap
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_UIFREMAP_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_UIFREMAP_ENABLE\fP   \fBTIM_CR1_UIFREMAP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_UIFREMAP_DISABLE   0x00000000U"
Update interrupt flag remap disabled 
.SS "#define TIM_UIFREMAP_ENABLE   \fBTIM_CR1_UIFREMAP\fP"
Update interrupt flag remap enabled 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
