.TH "TIM_ClearInput_Source" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ClearInput_Source \- TIM Clear Input Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLEARINPUTSOURCE_NONE\fP   0x10000000U"
.br
.ti -1c
.RI "#define \fBTIM_CLEARINPUTSOURCE_ETR\fP   0x20000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CLEARINPUTSOURCE_ETR   0x20000000U"
OCREF_CLR is connected to ETRF input 
.SS "#define TIM_CLEARINPUTSOURCE_NONE   0x10000000U"
OCREF_CLR is disabled 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
