.TH "TIM_Break2_Input_AF_Mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Break2_Input_AF_Mode \- TIM Break2 Input Alternate Function Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAK2_AFMODE_INPUT\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_BREAK2_AFMODE_BIDIRECTIONAL\fP   \fBTIM_BDTR_BK2BID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAK2_AFMODE_BIDIRECTIONAL   \fBTIM_BDTR_BK2BID\fP"
Break2 input BRK2 in bidirectional mode 
.SS "#define TIM_BREAK2_AFMODE_INPUT   0x00000000U"
Break2 input BRK2 in input mode 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
