.TH "TIMEx_Exported_Types" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Types \- TIM Extended Exported Types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTIM_HallSensor_InitTypeDef\fP"
.br
.RI "TIM Hall sensor Configuration Structure definition\&. "
.ti -1c
.RI "struct \fBTIMEx_BreakInputConfigTypeDef\fP"
.br
.RI "TIM Break/Break2 input configuration\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
