.TH "TIMEx_Break_Input_Source" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Break_Input_Source \- TIM Extended Break input source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAKINPUTSOURCE_BKIN\fP   0x00000001U                               /* !< An external source (GPIO) is connected to the BKIN pin  */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAKINPUTSOURCE_BKIN   0x00000001U                               /* !< An external source (GPIO) is connected to the BKIN pin  */"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
