.TH "TIMEx_Break_Input_Source_Enable" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Break_Input_Source_Enable \- TIM Extended Break input source enabling
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAKINPUTSOURCE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_BREAKINPUTSOURCE_ENABLE\fP   0x00000001U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAKINPUTSOURCE_DISABLE   0x00000000U"
Break input source is disabled 
.SS "#define TIM_BREAKINPUTSOURCE_ENABLE   0x00000001U"
Break input source is enabled 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
