.TH "TIMEx_BreakInputConfigTypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_BreakInputConfigTypeDef \- TIM Break/Break2 input configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g0xx_hal_tim_ex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBSource\fP"
.br
.ti -1c
.RI "uint32_t \fBEnable\fP"
.br
.ti -1c
.RI "uint32_t \fBPolarity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Break/Break2 input configuration\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint32_t TIMEx_BreakInputConfigTypeDef::Enable"
Specifies whether or not the break input source is enabled\&. This parameter can be a value of \fBTIM Extended Break input source enabling\fP 
.SS "uint32_t TIMEx_BreakInputConfigTypeDef::Polarity"
Specifies the break input source polarity\&. This parameter can be a value of \fBTIM Extended Break input polarity\fP 
.SS "uint32_t TIMEx_BreakInputConfigTypeDef::Source"
Specifies the source of the timer break input\&. This parameter can be a value of \fBTIM Extended Break input source\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
