.TH "TIMEx_Break_Input" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Break_Input \- TIM Extended Break input
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAKINPUT_BRK\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBTIM_BREAKINPUT_BRK2\fP   0x00000002U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAKINPUT_BRK   0x00000001U"
Timer break input 
.br
 
.SS "#define TIM_BREAKINPUT_BRK2   0x00000002U"
Timer break2 input 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
