.TH "TIMEx_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Constants \- TIM Extended Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTIM Extended Remapping\fP"
.br
.ti -1c
.RI "\fBTIM Extended Break input\fP"
.br
.ti -1c
.RI "\fBTIM Extended Break input source\fP"
.br
.ti -1c
.RI "\fBTIM Extended Break input source enabling\fP"
.br
.ti -1c
.RI "\fBTIM Extended Break input polarity\fP"
.br
.ti -1c
.RI "\fBTIM Extended Timer input selection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
