.TH "TIMEx_Timer_Input_Selection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Timer_Input_Selection \- TIM Extended Timer input selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_TIM1_TI1_GPIO\fP   0x00000000U                       /* !< TIM1_TI1 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM1_TI2_GPIO\fP   0x00000000U                       /* !< TIM1_TI2 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM1_TI3_GPIO\fP   0x00000000U                       /* !< TIM1_TI3 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM3_TI1_GPIO\fP   0x00000000U                       /* !< TIM3_TI1 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM3_TI2_GPIO\fP   0x00000000U                       /* !< TIM3_TI2 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM3_TI3_GPIO\fP   0x00000000U                       /* !< TIM3_TI3 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM14_TI1_GPIO\fP   0x00000000U                       /* !< TIM14_TI1 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM14_TI1_RTC\fP   0x00000001U                       /* !< TIM14_TI1 is connected to \fBRTC\fP clock */"
.br
.ti -1c
.RI "#define \fBTIM_TIM14_TI1_HSE_32\fP   0x00000002U                       /* !< TIM14_TI1 is connected to HSE div 32 */"
.br
.ti -1c
.RI "#define \fBTIM_TIM14_TI1_MCO\fP   0x00000003U                       /* !< TIM14_TI1 is connected to MCO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM16_TI1_GPIO\fP   0x00000000U                       /* !< TIM16_TI1 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM16_TI1_LSI\fP   0x00000001U                       /* !< TIM16_TI1 is connected to LSI */"
.br
.ti -1c
.RI "#define \fBTIM_TIM16_TI1_LSE\fP   0x00000002U                       /* !< TIM16_TI1 is connected to LSE */"
.br
.ti -1c
.RI "#define \fBTIM_TIM16_TI1_RTC_WAKEUP\fP   0x00000003U                       /* !< TIM16_TI1 is connected to TRC wakeup interrupt */"
.br
.ti -1c
.RI "#define \fBTIM_TIM17_TI1_GPIO\fP   0x00000000U                       /* !< TIM17_TI1 is connected to GPIO */"
.br
.ti -1c
.RI "#define \fBTIM_TIM17_TI1_HSE_32\fP   0x00000002U                       /* !< TIM17_TI1 is connected to HSE div 32 */"
.br
.ti -1c
.RI "#define \fBTIM_TIM17_TI1_MCO\fP   0x00000003U                       /* !< TIM17_TI1 is connected to MCO */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_TIM14_TI1_GPIO   0x00000000U                       /* !< TIM14_TI1 is connected to GPIO */"

.SS "#define TIM_TIM14_TI1_HSE_32   0x00000002U                       /* !< TIM14_TI1 is connected to HSE div 32 */"

.SS "#define TIM_TIM14_TI1_MCO   0x00000003U                       /* !< TIM14_TI1 is connected to MCO */"

.SS "#define TIM_TIM14_TI1_RTC   0x00000001U                       /* !< TIM14_TI1 is connected to \fBRTC\fP clock */"

.SS "#define TIM_TIM16_TI1_GPIO   0x00000000U                       /* !< TIM16_TI1 is connected to GPIO */"

.SS "#define TIM_TIM16_TI1_LSE   0x00000002U                       /* !< TIM16_TI1 is connected to LSE */"

.SS "#define TIM_TIM16_TI1_LSI   0x00000001U                       /* !< TIM16_TI1 is connected to LSI */"

.SS "#define TIM_TIM16_TI1_RTC_WAKEUP   0x00000003U                       /* !< TIM16_TI1 is connected to TRC wakeup interrupt */"

.SS "#define TIM_TIM17_TI1_GPIO   0x00000000U                       /* !< TIM17_TI1 is connected to GPIO */"

.SS "#define TIM_TIM17_TI1_HSE_32   0x00000002U                       /* !< TIM17_TI1 is connected to HSE div 32 */"

.SS "#define TIM_TIM17_TI1_MCO   0x00000003U                       /* !< TIM17_TI1 is connected to MCO */"

.SS "#define TIM_TIM1_TI1_GPIO   0x00000000U                       /* !< TIM1_TI1 is connected to GPIO */"

.SS "#define TIM_TIM1_TI2_GPIO   0x00000000U                       /* !< TIM1_TI2 is connected to GPIO */"

.SS "#define TIM_TIM1_TI3_GPIO   0x00000000U                       /* !< TIM1_TI3 is connected to GPIO */"

.SS "#define TIM_TIM3_TI1_GPIO   0x00000000U                       /* !< TIM3_TI1 is connected to GPIO */"

.SS "#define TIM_TIM3_TI2_GPIO   0x00000000U                       /* !< TIM3_TI2 is connected to GPIO */"

.SS "#define TIM_TIM3_TI3_GPIO   0x00000000U                       /* !< TIM3_TI3 is connected to GPIO */"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
