.TH "UART_DMA_Rx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_DMA_Rx \- UART DMA Rx
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_DMA_RX_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_DMA_RX_ENABLE\fP   \fBUSART_CR3_DMAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_DMA_RX_DISABLE   0x00000000U"
UART DMA RX disabled 
.SS "#define UART_DMA_RX_ENABLE   \fBUSART_CR3_DMAR\fP"
UART DMA RX enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
