.TH "UART_CR2_ADDRESS_LSB_POS" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_CR2_ADDRESS_LSB_POS \- UART Address-matching LSB Position In CR2 Register
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_CR2_ADDRESS_LSB_POS\fP   24U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_CR2_ADDRESS_LSB_POS   24U"
UART address-matching LSB position in CR2 register 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
