.TH "UARTEx_Word_Length" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UARTEx_Word_Length \- UARTEx Word Length
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_WORDLENGTH_7B\fP   \fBUSART_CR1_M1\fP"
.br
.ti -1c
.RI "#define \fBUART_WORDLENGTH_8B\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_WORDLENGTH_9B\fP   \fBUSART_CR1_M0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_WORDLENGTH_7B   \fBUSART_CR1_M1\fP"
7-bit long UART frame 
.SS "#define UART_WORDLENGTH_8B   0x00000000U"
8-bit long UART frame 
.SS "#define UART_WORDLENGTH_9B   \fBUSART_CR1_M0\fP"
9-bit long UART frame 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
