.TH "UART_Tx_Inv" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Tx_Inv \- UART Advanced Feature TX Pin Active Level Inversion
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_TXINV_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_TXINV_ENABLE\fP   \fBUSART_CR2_TXINV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_TXINV_DISABLE   0x00000000U"
TX pin active level inversion disable 
.SS "#define UART_ADVFEATURE_TXINV_ENABLE   \fBUSART_CR2_TXINV\fP"
TX pin active level inversion enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
