.TH "UART_DMA_Disable_on_Rx_Error" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_DMA_Disable_on_Rx_Error \- UART Advanced Feature DMA Disable On Rx Error
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_DMA_ENABLEONRXERROR\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_DMA_DISABLEONRXERROR\fP   \fBUSART_CR3_DDRE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_DMA_DISABLEONRXERROR   \fBUSART_CR3_DDRE\fP"
DMA disable on Reception Error 
.SS "#define UART_ADVFEATURE_DMA_ENABLEONRXERROR   0x00000000U"
DMA enable on Reception Error 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
