.TH "UART_IT_CLEAR_Flags" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_IT_CLEAR_Flags \- UART Interruption Clear Flags
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_CLEAR_PEF\fP   \fBUSART_ICR_PECF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_FEF\fP   \fBUSART_ICR_FECF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_NEF\fP   \fBUSART_ICR_NECF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_OREF\fP   \fBUSART_ICR_ORECF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_IDLEF\fP   \fBUSART_ICR_IDLECF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_TXFECF\fP   \fBUSART_ICR_TXFECF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_TCF\fP   \fBUSART_ICR_TCCF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_LBDF\fP   \fBUSART_ICR_LBDCF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_CTSF\fP   \fBUSART_ICR_CTSCF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_CMF\fP   \fBUSART_ICR_CMCF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_WUF\fP   \fBUSART_ICR_WUCF\fP"
.br
.ti -1c
.RI "#define \fBUART_CLEAR_RTOF\fP   \fBUSART_ICR_RTOCF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_CLEAR_CMF   \fBUSART_ICR_CMCF\fP"
Character Match Clear Flag 
.br
 
.SS "#define UART_CLEAR_CTSF   \fBUSART_ICR_CTSCF\fP"
CTS Interrupt Clear Flag 
.br
 
.SS "#define UART_CLEAR_FEF   \fBUSART_ICR_FECF\fP"
Framing Error Clear Flag 
.br
 
.SS "#define UART_CLEAR_IDLEF   \fBUSART_ICR_IDLECF\fP"
IDLE line detected Clear Flag 
.br
 
.SS "#define UART_CLEAR_LBDF   \fBUSART_ICR_LBDCF\fP"
LIN Break Detection Clear Flag 
.br
 
.SS "#define UART_CLEAR_NEF   \fBUSART_ICR_NECF\fP"
Noise Error detected Clear Flag 
.br
 
.SS "#define UART_CLEAR_OREF   \fBUSART_ICR_ORECF\fP"
Overrun Error Clear Flag 
.br
 
.SS "#define UART_CLEAR_PEF   \fBUSART_ICR_PECF\fP"
Parity Error Clear Flag 
.br
 
.SS "#define UART_CLEAR_RTOF   \fBUSART_ICR_RTOCF\fP"
UART receiver timeout clear flag 
.br
 
.SS "#define UART_CLEAR_TCF   \fBUSART_ICR_TCCF\fP"
Transmission Complete Clear Flag 
.br
 
.SS "#define UART_CLEAR_TXFECF   \fBUSART_ICR_TXFECF\fP"
TXFIFO empty clear flag 
.br
 
.SS "#define UART_CLEAR_WUF   \fBUSART_ICR_WUCF\fP"
Wake Up from stop mode Clear Flag 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
