.TH "UART_Request_Parameters" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Request_Parameters \- UART Request Parameters
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_AUTOBAUD_REQUEST\fP   \fBUSART_RQR_ABRRQ\fP"
.br
.ti -1c
.RI "#define \fBUART_SENDBREAK_REQUEST\fP   \fBUSART_RQR_SBKRQ\fP"
.br
.ti -1c
.RI "#define \fBUART_MUTE_MODE_REQUEST\fP   \fBUSART_RQR_MMRQ\fP"
.br
.ti -1c
.RI "#define \fBUART_RXDATA_FLUSH_REQUEST\fP   \fBUSART_RQR_RXFRQ\fP"
.br
.ti -1c
.RI "#define \fBUART_TXDATA_FLUSH_REQUEST\fP   \fBUSART_RQR_TXFRQ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_AUTOBAUD_REQUEST   \fBUSART_RQR_ABRRQ\fP"
Auto-Baud Rate Request 
.br
 
.SS "#define UART_MUTE_MODE_REQUEST   \fBUSART_RQR_MMRQ\fP"
Mute Mode Request 
.br
 
.SS "#define UART_RXDATA_FLUSH_REQUEST   \fBUSART_RQR_RXFRQ\fP"
Receive Data flush Request 
.br
 
.SS "#define UART_SENDBREAK_REQUEST   \fBUSART_RQR_SBKRQ\fP"
Send Break Request 
.br
 
.SS "#define UART_TXDATA_FLUSH_REQUEST   \fBUSART_RQR_TXFRQ\fP"
Transmit data flush Request 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
