.TH "UART_CR1_DEAT_ADDRESS_LSB_POS" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_CR1_DEAT_ADDRESS_LSB_POS \- UART Driver Enable Assertion Time LSB Position In CR1 Register
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_CR1_DEAT_ADDRESS_LSB_POS\fP   21U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_CR1_DEAT_ADDRESS_LSB_POS   21U"
UART Driver Enable assertion time LSB position in CR1 register 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
