.TH "UART_Overrun_Disable" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Overrun_Disable \- UART Advanced Feature Overrun Disable
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_OVERRUN_ENABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_OVERRUN_DISABLE\fP   \fBUSART_CR3_OVRDIS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_OVERRUN_DISABLE   \fBUSART_CR3_OVRDIS\fP"
RX overrun disable 
.SS "#define UART_ADVFEATURE_OVERRUN_ENABLE   0x00000000U"
RX overrun enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
