.TH "UART_MSB_First" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_MSB_First \- UART Advanced Feature MSB First
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_MSBFIRST_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_MSBFIRST_ENABLE\fP   \fBUSART_CR2_MSBFIRST\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_MSBFIRST_DISABLE   0x00000000U"
Most significant bit sent/received first disable 
.br
 
.SS "#define UART_ADVFEATURE_MSBFIRST_ENABLE   \fBUSART_CR2_MSBFIRST\fP"
Most significant bit sent/received first enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
