.TH "UART_Rx_Inv" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Rx_Inv \- UART Advanced Feature RX Pin Active Level Inversion
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_RXINV_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_RXINV_ENABLE\fP   \fBUSART_CR2_RXINV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_RXINV_DISABLE   0x00000000U"
RX pin active level inversion disable 
.SS "#define UART_ADVFEATURE_RXINV_ENABLE   \fBUSART_CR2_RXINV\fP"
RX pin active level inversion enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
