.TH "UART_DriverEnable_Polarity" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_DriverEnable_Polarity \- UART DriverEnable Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_DE_POLARITY_HIGH\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_DE_POLARITY_LOW\fP   \fBUSART_CR3_DEP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_DE_POLARITY_HIGH   0x00000000U"
Driver enable signal is active high 
.SS "#define UART_DE_POLARITY_LOW   \fBUSART_CR3_DEP\fP"
Driver enable signal is active low 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
