.TH "UART_LIN" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_LIN \- UART Local Interconnection Network mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_LIN_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_LIN_ENABLE\fP   \fBUSART_CR2_LINEN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_LIN_DISABLE   0x00000000U"
Local Interconnect Network disable 
.SS "#define UART_LIN_ENABLE   \fBUSART_CR2_LINEN\fP"
Local Interconnect Network enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
