.TH "UART_Exported_Functions_Group4" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Exported_Functions_Group4 \- Peripheral State and Error functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_UART_StateTypeDef\fP \fBHAL_UART_GetState\fP (const \fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "uint32_t \fBHAL_UART_GetError\fP (const \fBUART_HandleTypeDef\fP *huart)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "uint32_t HAL_UART_GetError (const \fBUART_HandleTypeDef\fP * huart)"

.SS "\fBHAL_UART_StateTypeDef\fP HAL_UART_GetState (const \fBUART_HandleTypeDef\fP * huart)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
