.TH "UART_LIN_Break_Detection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_LIN_Break_Detection \- UART LIN Break Detection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_LINBREAKDETECTLENGTH_10B\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_LINBREAKDETECTLENGTH_11B\fP   \fBUSART_CR2_LBDL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_LINBREAKDETECTLENGTH_10B   0x00000000U"
LIN 10-bit break detection length 
.SS "#define UART_LINBREAKDETECTLENGTH_11B   \fBUSART_CR2_LBDL\fP"
LIN 11-bit break detection length 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
