.TH "UART_DMA_Tx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_DMA_Tx \- UART DMA Tx
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_DMA_TX_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_DMA_TX_ENABLE\fP   \fBUSART_CR3_DMAT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_DMA_TX_DISABLE   0x00000000U"
UART DMA TX disabled 
.SS "#define UART_DMA_TX_ENABLE   \fBUSART_CR3_DMAT\fP"
UART DMA TX enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
