.TH "UART_WakeUp_Methods" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_WakeUp_Methods \- UART WakeUp Methods
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_WAKEUPMETHOD_IDLELINE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHOD_ADDRESSMARK\fP   \fBUSART_CR1_WAKE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_WAKEUPMETHOD_ADDRESSMARK   \fBUSART_CR1_WAKE\fP"
UART wake-up on address mark 
.SS "#define UART_WAKEUPMETHOD_IDLELINE   0x00000000U"
UART wake-up on idle line 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
