.TH "UARTEx_Exported_Functions_Group2" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UARTEx_Exported_Functions_Group2 \- UARTEx_Exported_Functions_Group2
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_UARTEx_WakeupCallback\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "void \fBHAL_UARTEx_RxFifoFullCallback\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.ti -1c
.RI "void \fBHAL_UARTEx_TxFifoEmptyCallback\fP (\fBUART_HandleTypeDef\fP *huart)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_UARTEx_RxFifoFullCallback (\fBUART_HandleTypeDef\fP * huart)"

.SS "void HAL_UARTEx_TxFifoEmptyCallback (\fBUART_HandleTypeDef\fP * huart)"

.SS "void HAL_UARTEx_WakeupCallback (\fBUART_HandleTypeDef\fP * huart)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
