.TH "UART_Data_Inv" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Data_Inv \- UART Advanced Feature Binary Data Inversion
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_DATAINV_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_DATAINV_ENABLE\fP   \fBUSART_CR2_DATAINV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_DATAINV_DISABLE   0x00000000U"
Binary data inversion disable 
.SS "#define UART_ADVFEATURE_DATAINV_ENABLE   \fBUSART_CR2_DATAINV\fP"
Binary data inversion enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
