.TH "UART_Rx_Tx_Swap" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Rx_Tx_Swap \- UART Advanced Feature RX TX Pins Swap
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_SWAP_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_SWAP_ENABLE\fP   \fBUSART_CR2_SWAP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_SWAP_DISABLE   0x00000000U"
TX/RX pins swap disable 
.SS "#define UART_ADVFEATURE_SWAP_ENABLE   \fBUSART_CR2_SWAP\fP"
TX/RX pins swap enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
