.TH "UART_Parity" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Parity \- UART Parity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_PARITY_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_PARITY_EVEN\fP   \fBUSART_CR1_PCE\fP"
.br
.ti -1c
.RI "#define \fBUART_PARITY_ODD\fP   (\fBUSART_CR1_PCE\fP | \fBUSART_CR1_PS\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_PARITY_EVEN   \fBUSART_CR1_PCE\fP"
Even parity 
.SS "#define UART_PARITY_NONE   0x00000000U"
No parity 
.br
 
.SS "#define UART_PARITY_ODD   (\fBUSART_CR1_PCE\fP | \fBUSART_CR1_PS\fP)"
Odd parity 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
