.TH "UARTEx_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UARTEx_Exported_Constants \- UARTEx Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUARTEx Word Length\fP"
.br
.ti -1c
.RI "\fBUARTEx WakeUp Address Length\fP"
.br
.ti -1c
.RI "\fBUARTEx FIFO mode\fP"
.br
.RI "UART FIFO mode\&. "
.ti -1c
.RI "\fBUARTEx TXFIFO threshold level\fP"
.br
.RI "UART TXFIFO threshold level\&. "
.ti -1c
.RI "\fBUARTEx RXFIFO threshold level\fP"
.br
.RI "UART RXFIFO threshold level\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
