.TH "UARTEx_FIFO_mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UARTEx_FIFO_mode \- UARTEx FIFO mode
.PP
 \- UART FIFO mode\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_FIFOMODE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_FIFOMODE_ENABLE\fP   \fBUSART_CR1_FIFOEN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UART FIFO mode\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_FIFOMODE_DISABLE   0x00000000U"
FIFO mode disable 
.SS "#define UART_FIFOMODE_ENABLE   \fBUSART_CR1_FIFOEN\fP"
FIFO mode enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
