.TH "UART_State" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_State \- UART State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_STATE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_STATE_ENABLE\fP   \fBUSART_CR1_UE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_STATE_DISABLE   0x00000000U"
UART disabled 
.br
 
.SS "#define UART_STATE_ENABLE   \fBUSART_CR1_UE\fP"
UART enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
