.TH "UARTEx_WakeUp_Address_Length" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UARTEx_WakeUp_Address_Length \- UARTEx WakeUp Address Length
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADDRESS_DETECT_4B\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADDRESS_DETECT_7B\fP   \fBUSART_CR2_ADDM7\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADDRESS_DETECT_4B   0x00000000U"
4-bit long wake-up address 
.SS "#define UART_ADDRESS_DETECT_7B   \fBUSART_CR2_ADDM7\fP"
7-bit long wake-up address 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
