.TH "UARTEx" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UARTEx \- UARTEx
.PP
 \- UART Extended HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUARTEx Exported Types\fP"
.br
.ti -1c
.RI "\fBUARTEx Exported Constants\fP"
.br
.ti -1c
.RI "\fBUARTEx Private Macros\fP"
.br
.ti -1c
.RI "\fBUARTEx_Exported_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UART Extended HAL module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
