.TH "UART_Exported_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Exported_Constants \- UART Exported Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUART State Code Definition\fP"
.br
.ti -1c
.RI "\fBUART Error Definition\fP"
.br
.ti -1c
.RI "\fBUART Number of Stop Bits\fP"
.br
.ti -1c
.RI "\fBUART Parity\fP"
.br
.ti -1c
.RI "\fBUART Hardware Flow Control\fP"
.br
.ti -1c
.RI "\fBUART Transfer Mode\fP"
.br
.ti -1c
.RI "\fBUART State\fP"
.br
.ti -1c
.RI "\fBUART Over Sampling\fP"
.br
.ti -1c
.RI "\fBUART One Bit Sampling Method\fP"
.br
.ti -1c
.RI "\fBUART Clock Prescaler\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature AutoBaud Rate Mode\fP"
.br
.ti -1c
.RI "\fBUART Receiver Timeout\fP"
.br
.ti -1c
.RI "\fBUART Local Interconnection Network mode\fP"
.br
.ti -1c
.RI "\fBUART LIN Break Detection\fP"
.br
.ti -1c
.RI "\fBUART DMA Tx\fP"
.br
.ti -1c
.RI "\fBUART DMA Rx\fP"
.br
.ti -1c
.RI "\fBUART Half Duplex Selection\fP"
.br
.ti -1c
.RI "\fBUART WakeUp Methods\fP"
.br
.ti -1c
.RI "\fBUART Request Parameters\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature Initialization Type\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature TX Pin Active Level Inversion\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature RX Pin Active Level Inversion\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature Binary Data Inversion\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature RX TX Pins Swap\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature Overrun Disable\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature Auto BaudRate Enable\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature DMA Disable On Rx Error\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature MSB First\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature Stop Mode Enable\fP"
.br
.ti -1c
.RI "\fBUART Advanced Feature Mute Mode Enable\fP"
.br
.ti -1c
.RI "\fBUART Address\-matching LSB Position In CR2 Register\fP"
.br
.ti -1c
.RI "\fBUART WakeUp From Stop Selection\fP"
.br
.ti -1c
.RI "\fBUART DriverEnable Polarity\fP"
.br
.ti -1c
.RI "\fBUART Driver Enable Assertion Time LSB Position In CR1 Register\fP"
.br
.ti -1c
.RI "\fBUART Driver Enable DeAssertion Time LSB Position In CR1 Register\fP"
.br
.ti -1c
.RI "\fBUART Interruptions Flag Mask\fP"
.br
.ti -1c
.RI "\fBUART polling\-based communications time\-out value\fP"
.br
.ti -1c
.RI "\fBUART Status Flags\fP"
.br
.ti -1c
.RI "\fBUART Interrupts Definition\fP"
.br
.ti -1c
.RI "\fBUART Interruption Clear Flags\fP"
.br
.ti -1c
.RI "\fBUART Reception type values\fP"
.br
.ti -1c
.RI "\fBUART RxEvent type values\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
