.TH "UART_RxEvent_Type_Values" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_RxEvent_Type_Values \- UART RxEvent type values
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_UART_RXEVENT_TC\fP   (0x00000000U)"
.br
.ti -1c
.RI "#define \fBHAL_UART_RXEVENT_HT\fP   (0x00000001U)"
.br
.ti -1c
.RI "#define \fBHAL_UART_RXEVENT_IDLE\fP   (0x00000002U)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_UART_RXEVENT_HT   (0x00000001U)"
RxEvent linked to Half Transfer event 
.br
 
.SS "#define HAL_UART_RXEVENT_IDLE   (0x00000002U)"
RxEvent linked to IDLE event 
.br
 
.SS "#define HAL_UART_RXEVENT_TC   (0x00000000U)"
RxEvent linked to Transfer Complete event 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
