.TH "UART_Receiver_Timeout" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Receiver_Timeout \- UART Receiver Timeout
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_RECEIVER_TIMEOUT_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_RECEIVER_TIMEOUT_ENABLE\fP   \fBUSART_CR2_RTOEN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_RECEIVER_TIMEOUT_DISABLE   0x00000000U"
UART Receiver Timeout disable 
.SS "#define UART_RECEIVER_TIMEOUT_ENABLE   \fBUSART_CR2_RTOEN\fP"
UART Receiver Timeout enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
