.TH "UART_Mute_Mode" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Mute_Mode \- UART Advanced Feature Mute Mode Enable
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_MUTEMODE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_MUTEMODE_ENABLE\fP   \fBUSART_CR1_MME\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_MUTEMODE_DISABLE   0x00000000U"
UART mute mode disable 
.SS "#define UART_ADVFEATURE_MUTEMODE_ENABLE   \fBUSART_CR1_MME\fP"
UART mute mode enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
