.TH "UART_Over_Sampling" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Over_Sampling \- UART Over Sampling
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_OVERSAMPLING_16\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_OVERSAMPLING_8\fP   \fBUSART_CR1_OVER8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_OVERSAMPLING_16   0x00000000U"
Oversampling by 16 
.SS "#define UART_OVERSAMPLING_8   \fBUSART_CR1_OVER8\fP"
Oversampling by 8 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
