.TH "UART_Half_Duplex_Selection" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_Half_Duplex_Selection \- UART Half Duplex Selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_HALF_DUPLEX_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_HALF_DUPLEX_ENABLE\fP   \fBUSART_CR3_HDSEL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_HALF_DUPLEX_DISABLE   0x00000000U"
UART half-duplex disabled 
.SS "#define UART_HALF_DUPLEX_ENABLE   \fBUSART_CR3_HDSEL\fP"
UART half-duplex enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
