.TH "UART_OneBit_Sampling" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_OneBit_Sampling \- UART One Bit Sampling Method
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_ENABLE\fP   \fBUSART_CR3_ONEBIT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ONE_BIT_SAMPLE_DISABLE   0x00000000U"
One-bit sampling disable 
.SS "#define UART_ONE_BIT_SAMPLE_ENABLE   \fBUSART_CR3_ONEBIT\fP"
One-bit sampling enable 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
