.TH "UART_ClockPrescaler" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_ClockPrescaler \- UART Clock Prescaler
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV2\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV4\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV6\fP   0x00000003U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV8\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV10\fP   0x00000005U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV12\fP   0x00000006U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV16\fP   0x00000007U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV32\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV64\fP   0x00000009U"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV128\fP   0x0000000AU"
.br
.ti -1c
.RI "#define \fBUART_PRESCALER_DIV256\fP   0x0000000BU"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_PRESCALER_DIV1   0x00000000U"
fclk_pres = fclk 
.br
 
.SS "#define UART_PRESCALER_DIV10   0x00000005U"
fclk_pres = fclk/10 
.br
 
.SS "#define UART_PRESCALER_DIV12   0x00000006U"
fclk_pres = fclk/12 
.br
 
.SS "#define UART_PRESCALER_DIV128   0x0000000AU"
fclk_pres = fclk/128 
.SS "#define UART_PRESCALER_DIV16   0x00000007U"
fclk_pres = fclk/16 
.br
 
.SS "#define UART_PRESCALER_DIV2   0x00000001U"
fclk_pres = fclk/2 
.br
 
.SS "#define UART_PRESCALER_DIV256   0x0000000BU"
fclk_pres = fclk/256 
.SS "#define UART_PRESCALER_DIV32   0x00000008U"
fclk_pres = fclk/32 
.br
 
.SS "#define UART_PRESCALER_DIV4   0x00000002U"
fclk_pres = fclk/4 
.br
 
.SS "#define UART_PRESCALER_DIV6   0x00000003U"
fclk_pres = fclk/6 
.br
 
.SS "#define UART_PRESCALER_DIV64   0x00000009U"
fclk_pres = fclk/64 
.br
 
.SS "#define UART_PRESCALER_DIV8   0x00000004U"
fclk_pres = fclk/8 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
