.TH "UART_AutoBaudRate_Enable" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART_AutoBaudRate_Enable \- UART Advanced Feature Auto BaudRate Enable
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ADVFEATURE_AUTOBAUDRATE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBUART_ADVFEATURE_AUTOBAUDRATE_ENABLE\fP   \fBUSART_CR2_ABREN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define UART_ADVFEATURE_AUTOBAUDRATE_DISABLE   0x00000000U"
RX Auto Baud rate detection enable 
.br
 
.SS "#define UART_ADVFEATURE_AUTOBAUDRATE_ENABLE   \fBUSART_CR2_ABREN\fP"
RX Auto Baud rate detection disable 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
