.TH "UART" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART \- UART
.PP
 \- HAL UART module driver\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBUART Exported Types\fP"
.br
.ti -1c
.RI "\fBUART Exported Constants\fP"
.br
.ti -1c
.RI "\fBUART Exported Macros\fP"
.br
.ti -1c
.RI "\fBUART Private Macros\fP"
.br
.ti -1c
.RI "\fBUART Private variables\fP"
.br
.ti -1c
.RI "\fBUART Exported Functions\fP"
.br
.ti -1c
.RI "\fBUART Private Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HAL UART module driver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
