.TH "UTILS_LL_Private_Constants" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILS_LL_Private_Constants \- UTILS Private Constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLL_MAX_DELAY\fP   0xFFFFFFFFU"
.br
.ti -1c
.RI "#define \fBUID_BASE_ADDRESS\fP   \fBUID_BASE\fP"
.br
.RI "Unique device ID register base address\&. "
.ti -1c
.RI "#define \fBFLASHSIZE_BASE_ADDRESS\fP   \fBFLASHSIZE_BASE\fP"
.br
.RI "Flash size data register base address\&. "
.ti -1c
.RI "#define \fBPACKAGE_BASE_ADDRESS\fP   \fBPACKAGE_BASE\fP"
.br
.RI "Package data register base address\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASHSIZE_BASE_ADDRESS   \fBFLASHSIZE_BASE\fP"

.PP
Flash size data register base address\&. 
.SS "#define LL_MAX_DELAY   0xFFFFFFFFU"

.SS "#define PACKAGE_BASE_ADDRESS   \fBPACKAGE_BASE\fP"

.PP
Package data register base address\&. 
.SS "#define UID_BASE_ADDRESS   \fBUID_BASE\fP"

.PP
Unique device ID register base address\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
