.TH "UTILS_LL_Exported_Functions" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTILS_LL_Exported_Functions \- UTILS Exported Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDEVICE ELECTRONIC SIGNATURE\fP"
.br
.ti -1c
.RI "\fBDELAY\fP"
.br
.ti -1c
.RI "\fBSYSTEM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
