.TH "WWDG_TypeDef" 3 "Version 1.0.0" "Radar" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_TypeDef \- Window WATCHDOG\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32g030xx\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Window WATCHDOG\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t WWDG_TypeDef::CFR"
WWDG Configuration register, Address offset: 0x04 
.SS "\fB__IO\fP uint32_t WWDG_TypeDef::CR"
WWDG Control register, Address offset: 0x00 
.SS "\fB__IO\fP uint32_t WWDG_TypeDef::SR"
WWDG Status register, Address offset: 0x08 

.SH "Author"
.PP 
Generated automatically by Doxygen for Radar from the source code\&.
